---
title: "GER Sensitivity Analysis - source - Preg/Lact"
author: "S. Agbayani"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  github_document:
  html_document:
  pdf_document:
    
editor_options:
  chunk_output_type: console
classoption: landscape
---



```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(error = TRUE)
#quiet col types messages
options(readr.show_col_types = FALSE)

## Setup

# Initialize all libraries, set paths for output figures, then import the gw_observations.csv
# install.packages("tidyr")
# install.packages("readr")
# install.packages("tidyverse")
# install.packages("dplyr")
# install.packages("ggplot2")
# install.packages("knitr")
# install.packages("nls2")
# install.packages("nlstools")
# install.packages("nlme")
# install.packages("minpack.lm")
# install.packages("scales")
# install.packages("ggpmisc")
# install.packages("extrafont")
# install.packages("gtable")
# install.packages("ggpubr")

library(tidyverse)
library(tidyr)
library(readr)
library(dplyr)
library(ggplot2)
library(knitr)
library(nls2)
library(nlstools)
library(nlme)
library(minpack.lm)
library(scales)
library(ggpmisc)
library(reshape2)
library(extrafont)
library(gtable)
library(ggpubr)

#source("functions.R")

```


```{r declare functions and global variables, include=FALSE}

# **Declare custom functions and global variables**
########## Specify Decimal function ############################
# 
# For use in labelling the plots with equations, and rounding up the coefficients
# to a specific no. of decimal places
specify_decimal <- function(x, k) format(round(x, k), nsmall=k)


############ Multiple plot function######################
#
# ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
# - cols:   Number of columns in layout
# - layout: A matrix specifying the layout. If present, 'cols' is ignored.
#
# If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
# then plot 1 will go in the upper left, 2 will go in the upper right, and
# 3 will go all the way across the bottom.
#
# Code extracted from Cookbook for R. This site is powered by knitr and Jekyll. 
# If you find any errors, please email winston@stdout.org

multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}


########### functions used for carry out the fit ########

## this function is avaible in: 
# http://www.leg.ufpr.br/~walmes/cursoR/ciaeear/as.lm.R   or in 
# https://gist.github.com/TonyLadson/2d63ca70eef92583001dece607127759 (from the line 269)

##### as.lm function: ######

        as.lm <- function(object, ...) UseMethod("as.lm")

        as.lm.nls <- function(object, ...) {
            if (!inherits(object, "nls")) {
                w <- paste("expected object of class nls but got object of class:", 
                    paste(class(object), collapse = " "))
                warning(w)
            }

            gradient <- object$m$gradient()
            if (is.null(colnames(gradient))) {
                colnames(gradient) <- names(object$m$getPars())
            }

            response.name <- if (length(formula(object)) == 2) "0" else 
                as.character(formula(object)[[2]])

            lhs <- object$m$lhs()
            L <- data.frame(lhs, gradient)
            names(L)[1] <- response.name

            fo <- sprintf("%s ~ %s - 1", response.name, 
                paste(colnames(gradient), collapse = "+"))
            fo <- as.formula(fo, env = as.proto.list(L))

            do.call("lm", list(fo, offset = substitute(fitted(object))))

        }

############## End as.lm function 



############### proto function: ############
#### proto function avaible in https://github.com/hadley/proto/blob/master/R/proto.R

proto <- function(. = parent.env(envir), expr = {},
                   envir = new.env(parent = parent.frame()), ...,
                   funEnvir = envir) {
  parent.env(envir) <- .
  envir <- as.proto.environment(envir)  # must do this before eval(...)
  # moved eval after for so that ... always done first
  # eval(substitute(eval(quote({ expr }))), envir)
  dots <- list(...); names <- names(dots)
  for (i in seq_along(dots)) {
    assign(names[i], dots[[i]], envir = envir)
    if (!identical(funEnvir, FALSE) && is.function(dots[[i]]))
      environment(envir[[names[i]]]) <- funEnvir
  }
  eval(substitute(eval(quote({
    expr
  }))), envir)
  if (length(dots))
    as.proto.environment(envir)
  else
    envir
}

#' @export
#' @rdname proto
as.proto <- function(x, ...) {
  UseMethod("as.proto")
}

#' @export
#' @rdname proto
as.proto.environment <- function(x, ...) {
  assign(".that", x, envir = x)
  assign(".super", parent.env(x), envir = x)
  structure(x, class = c("proto", "environment"))
}

#' @export
#' @rdname proto
as.proto.proto <- function(x, ...) {
  x
}
as.proto.list <- function(x, envir, parent, all.names = FALSE, ...,
                          funEnvir = envir, SELECT = function(x) TRUE) {
  if (missing(envir)) {
    if (missing(parent))
      parent <- parent.frame()
    envir <- if (is.proto(parent))
      parent$proto(...)
    else
      proto(parent, ...)
  }
  for (s in names(x))
    if (SELECT(x[[s]])) {
      assign(s, x[[s]], envir = envir)
      if (is.function(x[[s]]) && !identical(funEnvir, FALSE))
        environment(envir[[s]]) <- funEnvir
    }
  if (!missing(parent))
    parent.env(envir) <- parent
  as.proto.environment(envir)  # force refresh of .that and .super
}

#' @export
"$<-.proto" <- function(this,s,value) {
  if (s == ".super")
    parent.env(this) <- value
  if (is.function(value))
    environment(value) <- this
  this[[as.character(substitute(s))]] <- value
  this
}
is.proto <- function(x) inherits(x, "proto")

#' @export
"$.proto" <- function(x, name) {
  inherits <- substr(name, 1, 2) != ".."

  res <- get(name, envir = x, inherits = inherits)
  if (!is.function(res))
    return(res)

  if (deparse(substitute(x)) %in% c(".that", ".super"))
    return(res)

  structure(
    function(...) res(x, ...),
    class = "protoMethod",
    method = res
  )
}

#' @export
print.protoMethod <- function(x, ...) {
  cat("<ProtoMethod>\n")
  print(attr(x, "method"), ...)
}

# modified from Tom Short's original
#' @export
str.proto <- function(object, max.level = 1, nest.lev = 0,
                      indent.str = paste(rep.int(" ", max(0, nest.lev + 1)), collapse = ".."),
                      ...) {
  cat("proto", name.proto(object), "\n")
  Lines <- utils::capture.output(utils::str(
    as.list(object), max.level = max.level,
    nest.lev = nest.lev, ...
  ))[-1]
  for (s in Lines)
    cat(s, "\n")
  if (is.proto(parent.env(object))) {
    cat(indent.str, "parent: ", sep = "")
    utils::str(parent.env(object), nest.lev = nest.lev + 1, ...)
  }
}

#' @export
print.proto <- function(x, ...) {
  if (!exists("proto_print", envir = x, inherits = TRUE))
    return(NextMethod())

  x$proto_print(...)
}

############# End proto function 

############ PredictNLS - for confidence intervals  ##########
# Source: https://rmazing.wordpress.com/2013/08/14/predictnls-part-1-monte-carlo-simulation-confidence-intervals-for-nls-models/

predictNLS <- function(object,newdata,level = 0.95, nsim = 10000,
                       ...){
    require(MASS, quietly = TRUE)
    ## get right-hand side of formula
    RHS <- as.list(object$call$formula)[[3]]
    EXPR <- as.expression(RHS)
   
    ## all variables in model
    VARS <- all.vars(EXPR)
   
    ## coefficients
    COEF <- coef(object)
   
    ## extract predictor variable    
    predNAME <- setdiff(VARS, names(COEF))  
   
    ## take fitted values, if 'newdata' is missing
    if (missing(newdata)) {
        newdata <- eval(object$data)[predNAME]
        colnames(newdata) <- predNAME
        }
       
    ## check that 'newdata' has same name as predVAR
    if (names(newdata)[1] != predNAME) stop("newdata should have name '",
                                            predNAME, "'!")
   
    ## get parameter coefficients
    COEF <- coef(object)
     
    ## get variance-covariance matrix
    VCOV <- vcov(object)
   
    ## augment variance-covariance matrix for 'mvrnorm' 
    ## by adding a column/row for 'error in x'
    NCOL <- ncol(VCOV)
    ADD1 <- c(rep(0, NCOL))
    ADD1 <- matrix(ADD1, ncol = 1)
    colnames(ADD1) <- predNAME
    VCOV <- cbind(VCOV, ADD1)
    ADD2 <- c(rep(0, NCOL + 1))
    ADD2 <- matrix(ADD2, nrow = 1)
    rownames(ADD2) <- predNAME
    VCOV <- rbind(VCOV, ADD2) 
         
    ## iterate over all entries in 'newdata' as in usual 'predict.' functions
    NR <- nrow(newdata)
    respVEC <- numeric(NR)
    seVEC <- numeric(NR)
    varPLACE <- ncol(VCOV)   
   
    ## define counter function
    counter <- function (i) {
        if (i%%10 == 0) 
            cat(i)
        else cat(".")
        if (i%%50 == 0) 
            cat("\n")
        flush.console()
        }
   
    outMAT <- NULL 
   
    for (i in 1:NR) {
        counter(i)
        ## get predictor values and optional errors
    predVAL <- newdata[i, 1]
    if (ncol(newdata) == 2) predERROR <- newdata[i, 2] else predERROR <- 0
    names(predVAL) <- predNAME  
    names(predERROR) <- predNAME  
     
    ## create mean vector for 'mvrnorm'
    MU <- c(COEF, predVAL)
     
    ## create variance-covariance matrix for 'mvrnorm'
    ## by putting error^2 in lower-right position of VCOV
    newVCOV <- VCOV
    newVCOV[varPLACE, varPLACE] <- predERROR^2
     
    ## create MC simulation matrix
    simMAT <- mvrnorm(n = nsim, mu = MU, Sigma = newVCOV, empirical = TRUE)
     
    ## evaluate expression on rows of simMAT
    EVAL <- try(eval(EXPR, envir = as.data.frame(simMAT)), silent = TRUE)
    if (inherits(EVAL, "try-error")) stop("There was an error evaluating the simulations!")
     
    ## collect statistics
    PRED <- data.frame(predVAL)
    colnames(PRED) <- predNAME   
    FITTED <- predict(object, newdata = data.frame(PRED))
    MEAN.sim <- mean(EVAL, na.rm = TRUE)
    SD.sim <- sd(EVAL, na.rm = TRUE)
    MEDIAN.sim <- median(EVAL, na.rm = TRUE)
    MAD.sim <- mad(EVAL, na.rm = TRUE)  #median absolute deviation
    QUANT <- quantile(EVAL, c((1 - level)/2, level + (1 - level)/2))
    RES <- c(FITTED, MEAN.sim, SD.sim, MEDIAN.sim, MAD.sim, QUANT[1], QUANT[2])
    outMAT <- rbind(outMAT, RES)
  }
   
  colnames(outMAT) <- c("fit", "mean", "sd", "median", "mad", names(QUANT[1]), names(QUANT[2]))
  rownames(outMAT) <- NULL
   
  cat("\n")
   
  return(outMAT)  
}

##########end PredictNLS ##########

        
```   



```{r setpaths}       
# Set path for output figures: 
Figurespath <- paste0(getwd(), "/gross_energetic_reqs/figures", collapse = NULL)
Figurespath

# Set path for input & output data  
datapath <- paste0(getwd(), "/data", collapse = NULL) 
datapath

```


```{r read_in_data}
## Read data in Activity Cost Reference, Production Cost, Es
A_cost_reference <- as_tibble(
  read_csv("data/ActivityCost_ReferenceData_BreathsPerDay_Table_VA_2017_original_sources.csv"),
  col_types = (list(cols(  ID = col_double(),
                           Lifestage = col_character(),
                           Description = col_character(),
                           Activity_stages = col_character(),
                           no_days = col_double(),
                           source_no_days = col_character(),
                           bpm = col_double(),
                           se_bpm = col_double(),
                           source_bpm = col_character(),
                           age_yrs = col_double(),
                           age_yrs_min = col_double(),
                           age_yrs_max = col_double(),
                           pct_O2 = col_double(),
                           pct_O2_sd = col_double()
  )
  )
  )
)

kable(A_cost_reference)

Activity_days <- A_cost_reference %>% select(Lifestage, Activity_stages, no_days) %>%  
  group_by(Lifestage, Activity_stages) %>% 
  summarise(no_days = sum(no_days))

kable(Activity_days)

P_cost_table <- as_tibble(
  read_csv("data/P_cost_table_phase1.csv"),
  col_types = (list(cols(age_mth = col_double(),
                         age_yrs = col_double(),
                         mean_masschange = col_double(),
                         sd_masschange = col_double(),
                         sex = col_character(),
                         mean_P = col_double(),
                         sd_P = col_double(),
                         quant025 = col_double(),
                         quant975 = col_double(),
                         p_lipid = col_double(),
                         p_protein = col_double()
  )
  )
  )
) 


#P_cost_table <- P_cost_table %>% dplyr::filter(age_yrs >= 0)
kable(head(P_cost_table))


P_cost_table_preg  <-  as_tibble(
  read_csv("data/P_cost_table_preg.csv"),
  col_types = list(cols(age_yrs = col_double(),
                        mean_masschange = col_double(),
                        sd_masschange = col_double(),
                        sex = col_character(),
                        mean_P = col_double(),
                        sd_P = col_double(),
                        p_lipid = col_double(),
                        p_protein = col_double()
  )
  )
)


P_cost_table_preg$Ts <-  396

P_cost_table_lact <- as_tibble(
  read_csv("data/P_cost_table_lact.csv"),
  col_types = list(cols(age_yrs = col_double(),
                        mean_masschange = col_double(),
                        sd_masschange = col_double(),
                        sex = col_character(),
                        mean_P = col_double(),
                        sd_P = col_double(),
                        p_lipid = col_double(),
                        p_protein = col_double()
  )
  )
)

P_cost_table_lact$Ts <-  365

Es_preg_table <- as_tibble(
  read_csv("data/Es_sensAnalysis_preg_peryear_source_bpm.csv"),
  col_types = (list(cols(age_yrs = col_double(),
                         Lifestage = col_character(),
                         no_days = col_double(),
                         Es = col_double(),
                         Es_sd = col_double()
  )
  )
  )
)
kable(head(Es_preg_table))





Es_lact_table <- as_tibble(
  read_csv("data/Es_sensAnalysis_lact_peryear_source_bpm.csv"),
  col_types = (list(cols(age_yrs = col_double(),
                         Lifestage = col_character(),
                         no_days = col_double(),
                         Es = col_double(),
                         Es_sd = col_double()
  )                                   
  )
  )
)


kable(head(Es_lact_table))

mass_table <- as_tibble(
  read_csv("data/mass_table.csv"),
  col_types = (list(cols(age_yrs = col_double(),
                         mean_mass = col_double(),
                         sd_mass = col_double(),
                         mean_lwr = col_double(),
                         mean_upr = col_double(),
                         quant025 = col_double(),
                         quant975 = col_double(),
                         female_mass = col_double(),
                         male_mass = col_double()
  )
  )
  )
)


mean_masschange <- as_tibble(
  read_csv("data/mean_masschange.csv"),
  col_types = (list(cols(age_yrs = col_double(),
                         mean_masschange = col_double(),
                         sd_masschange = col_double(),
                         sex = col_character(),
                         age_mth = col_double()
  )
  )
  )
)


mean_masschange <- mean_masschange %>% dplyr::filter(age_yrs >=0)
kable(head(mean_masschange))

mean_masschange_peryear <- as_tibble(
  read_csv("data/mean_masschange_per_year.csv"),
  col_types = (list(cols(age_yrs = col_double(),
                         mean_masschange = col_double(),
                         sd_masschange = col_double(),
                         sex = col_character()
  )
  )
  )
)

mean_masschange_peryear <- mean_masschange_peryear %>% dplyr::filter(age_yrs >= 0)
kable(head(mean_masschange_peryear))


age_yr_tibble <- as_tibble(
  read_csv("data/age_yr_tibble.csv"), 
  col_types = (list(ID = col_integer(),
                    month = col_character(),
                    no_days_in_mth = col_double(),
                    age_mth = col_double(),
                    no_days_cumul = col_double(),
                    age_yrs = col_double()
  )
  )
)

kable(age_yr_tibble)

predict_GER_table_sensAnalysis_phase2  <- as_tibble(
  read_csv("data/predict_GER_table_sensAnalysis_phase2 .csv"),
  col_types = (list(ID = col_integer(),
                    phase = col_double(),
                    age_yrs = col_double(),
                    sex = col_character(),
                    MC_variable = col_character(),
                    mean_GER = col_double(),
                    GER_sd = col_double(),
                    quant025 = col_double(),
                    quant975 = col_double(),
                    GER_foraging = col_double(),
                    sd_foraging = col_double(),
                    quant025_foraging = col_double(),
                    quant975_foraging = col_double(),
                    FR_foraging = col_double(),
                    FR_sd_foraging = col_double(),
                    FR_quant025 = col_double(),
                    FR_quant975 = col_double(),
                    Ts = col_double(),
                    mean_mass = col_double(),
                    percent_body_weight_consumed = col_double()
  )))





TotalGER_birth_to_weaning_tibble <- as_tibble(
  read_csv("data/TotalGER_birth_to_weaning_tibble.csv"),
  col_types = (list(ID = col_integer(),
                    age_range = col_character(),
                    sex = col_character(),
                    Total_GER = col_double(),
                    Total_GER_sd = col_double(), 
                    details = col_character()
  )))


kable(TotalGER_birth_to_weaning_tibble)



```



```{r define_variables}

#Energy Density values
ED_milk = 22.33 #MJ/kg   Average between Tomilin 1946 and Zenkovich 1938,    (Sumich 1986 - cited 22.4  MJ/kg)


MC_reps = 10000


```

```{r GER_preg}

predict_GER_table_sensAnalysis_preg <- as.data.frame(matrix(ncol = 23, nrow = 0))

cnames <- c("phase", "age_yrs", "MC_variable", 
            "mean_GER", "GER_sd", 
            "quant025", "quant975", 
            "GER_foraging", "sd_foraging",
            "quant025_foraging", "quant975_foraging",   #2.5% and 97.5% quantile from bootstrap estimates
            "FR_foraging", "FR_sd_foraging",
            "FR_quant025","FR_quant975",
            "Hg", "Hg_sd",
            "P_nb", "GERcalf_6mths", 
            "mass","mass_sd", "pctbodywt", "pctbodywt_sd"
)            

colnames(predict_GER_table_sensAnalysis_preg) <- cnames

predict_GER_table_sensAnalysis_preg <- as_tibble(
  predict_GER_table_sensAnalysis_preg,
  col_types = (list(ID = col_integer(),
                    phase = col_character(),
                    age_yrs = col_double(), 
                    MC_variable = col_character(), 
                    mean_GER = col_double(), 
                    GER_sd = col_double(), 
                    quant025 = col_double(), 
                    quant975 = col_double(), 
                    GER_foraging = col_double(),
                    sd_foraging = col_double(), 
                    quant025_foraging = col_double(),
                    quant975_foraging = col_double(),
                    FR_foraging = col_double(),
                    FR_sd_foraging = col_double(),
                    FR_quant025 = col_double(),
                    FR_quant975 = col_double(),
                    Hg = col_double(),
                    Hg_sd = col_double(),
                    P_nb = col_double(),
                    GERcalf_6mths = col_double(),
                    mass = col_double(),
                    mass_sd = col_double(),
                    pctbodywt = col_double(),
                    pctbodywt_sd = col_double()
  )
  )
)





for (i in seq(from = 8, to = 75, by = 1)){
  for (MC_var in c("all","Hg","GER_calf", 
                   "P_nb", "P_cost", "Es", "E_FnU")){
    age <-  i
    s <- "Female"
    phase <- "Pregnant"
    
    # Mass values
    mass_foetus <- mass_table %>% dplyr::filter(age_yrs == 0) 
    mass_foetus_40pct <- mass_foetus$mean_mass * 0.4 
    
    mass_female <- mass_table %>% 
      dplyr::filter(age_yrs == age) %>% 
      dplyr::select(female_mass) %>% 
      pull(female_mass)
    mass_preg <- mass_female + mass_foetus_40pct
    
    if (MC_var == "all"){
      mass_foetus_40pct_sd <- mass_foetus$sd_mass * 0.4
      mass_female_sd <- mass_table %>% 
        dplyr::filter(age_yrs == age) %>% 
        dplyr::select(sd_mass) %>% 
        pull(sd_mass)
      mass_preg_sd <- sqrt((mass_female_sd^2)+(mass_foetus_40pct_sd^2))
    } else {
      mass_preg_sd <-0
    }
    
    # Mass of newborn (for Hg calcs)
    Mnb <- mass_foetus$mean_mass
    if (MC_var == "all" || MC_var == "Hg"){
      sd_Mnb <- mass_foetus$sd_mass  # sd of mass of newborn (kg)
    } else {
      sd_Mnb <-  0
    }
    
    
    # Production cost values
    P_cost_i <- P_cost_table_preg %>%
      dplyr::filter(P_cost_table_preg$age_yrs == age)
    P_cost_i <- P_cost_i %>%
      dplyr::filter(P_cost_i$sex == s)
    
    mean_P <- P_cost_i$mean_P_perday * 396
    
    if (MC_var == "all" || MC_var == "P_cost"){
      sd_P <-  P_cost_i$sd_P_perday * 396
    } else {
      sd_P <-  0
    }
    
    # Production cost - newborn
    P_nb_table <- P_cost_table %>% 
      dplyr::filter(age_yrs == 0 & sex == "N/A")
    
    P_nb <- P_nb_table %>% pull(mean_P)
    if (MC_var == "all" || MC_var == "P_nb"){
      P_nb_sd <- P_nb_table %>% pull(sd_P)
    } else {
      P_nb_sd <- 0
    }
    
    # Energetic expenditure values
    Es_table_i <- Es_preg_table %>%
      dplyr::filter(Es_preg_table$age_yrs  == age)
    
    Es <- Es_table_i$Es
    if (MC_var == "all" || MC_var == "Es"){
      Es_sd <- Es_table_i$Es_sd
    } else {
      Es_sd <- 0
    }
      
    T_s <- Es_table_i$no_days
    
    #Fecal and Urinary cost - E_FnU
    E_FnU_min = 0.740
    E_FnU_max = 0.858
    E_FnU_mean = (E_FnU_min + E_FnU_max)/2
    
    #Energetic density of Prey - ED_prey
    ED_prey_mean = 2.90 #MJ/kg  from average I calculated... 
    ED_prey_min = 2.51   #from Coyle et al. 2007
    ED_prey_max = 3.41   #from Stoker 1978
    
    if (MC_var == "all"){
      ED_prey_sd = 0.0408  #calculated from table 3  
    } else {
      ED_prey_sd = 0
    }
    
    # GER calf 6 mths
    GERcalf_6mths_tibble <- TotalGER_birth_to_weaning_tibble %>% 
      dplyr::filter(age_range == "0 to 6 mths") 
    
    GERcalf_6mths <- GERcalf_6mths_tibble %>% pull(Total_GER)
    
    if (MC_var == "all" || MC_var == "GERcalf"){
      GERcalf_6mths_sd <- GERcalf_6mths_tibble$Total_GER_sd
    } else {
      GERcalf_6mths_sd <- 0
    }
    
   # Monte Carlo - Production cost 
    set.seed(12345)
    MC_vars_i <- as_tibble(rnorm(MC_reps, mean_P, sd_P))
    names(MC_vars_i)[1] <- "P_cost"
    
    MC_vars_i$sex <- s   # do i need to identify sex here?
    MC_vars_i$GER <- NA
    MC_vars_i<- MC_vars_i %>%  
      dplyr::select(sex, GER, everything()) #move sex to the first column
    
    # Monte carlo - Es
    set.seed(12345)
    Es_i <-  as_tibble(rnorm(MC_reps, Es, Es_sd))
    names(Es_i)[1] <- "Es"
    
    MC_vars_i <- cbind(MC_vars_i, Es_i)
    
    #### Monte carlo - Fecal and urinary waste - E_FnU
    set.seed(12345)
    if (MC_var == "E_FnU" || MC_var == "all"){
      E_FnU_i <- as_tibble(runif(MC_reps, min = E_FnU_min, max = E_FnU_max)) 
    } else {
      E_FnU_i <- as_tibble(runif(MC_reps, min = E_FnU_mean, max = E_FnU_mean)) 
    }
    names(E_FnU_i)[1] <- "E_FnU"
    
    MC_vars_i <- cbind(MC_vars_i, E_FnU_i)

    #### Monte carlo - Energetic density of prey - ED_prey
    ED_prey_i <- as_tibble(rnorm(MC_reps, ED_prey_mean, ED_prey_sd))
    names(ED_prey_i)[1] <- "ED_prey"
    
    MC_vars_i <- cbind(MC_vars_i, ED_prey_i)
    
    # Monte Carlo - mass (for pct body wt calcs)
    set.seed(12345)
    mass_i <- as_tibble(rnorm(MC_reps, mass_preg, mass_preg_sd))
    names(mass_i)[1] <- "mass"
    
    MC_vars_i <- cbind(MC_vars_i, mass_i)
    
    # Heat increment of gestation
    set.seed(1234)
    Mnb_i <- rnorm(MC_reps, Mnb, sd_Mnb)
    Mnb_table <- as_tibble(Mnb_i)
    names(Mnb_table)[1] <- "Mnb"
    
    #(Brody 1945)  Q (Cal) = 4400 Cal x M^1.2 (kg)
    Hg <- 18.41 * (Mnb_table$Mnb^1.2)  
    # Hg <- 18.41 MJ x M^1.2 kg         
    Hg_i <- as_tibble(Hg)
    names(Hg_i)[1] <- "Hg"
    MC_vars_i <- cbind(MC_vars_i, Hg_i)
    
    #Production cost of newborn calf
    P_nb_i <- as_tibble(rnorm(MC_reps, P_nb, P_nb_sd))
    names(P_nb_i)[1] <- "P_nb"
    MC_vars_i <- cbind(MC_vars_i, P_nb_i)
    
    #Cost of nursing calf for first 6 mths
    #GER from birth to 6mths
    GERcalf_0to6m <- as_tibble(rnorm(MC_reps, GERcalf_6mths, GERcalf_6mths_sd))
    #names(GERcalf_0to6m)[1] <- "GERcalf_0to6m"
    GERcalf_0to6m <- GERcalf_0to6m %>% rename("GERcalf_0to6m"="value")
    MC_vars_i <- cbind(MC_vars_i, GERcalf_0to6m)
    
    
    # Pcost of mother
    P_cost <- MC_vars_i$P_cost 
    Es <- MC_vars_i$Es
    E_FnU <- MC_vars_i$E_FnU
    #E_HIF <- MC_vars_i$E_HIF
    Hg <- MC_vars_i$Hg
    P_nb <- MC_vars_i$P_nb
    GERcalf_0to6m <- MC_vars_i$GERcalf_0to6m
    
    #GER  preg  = GER preg whale + GER calf 6mths (lactation) 
    #Es includes digestion, maintenance and activity          

    MC_vars_i$GER <- ((P_cost + Es + Hg + P_nb + GERcalf_0to6m)/396)/E_FnU  #preg total days = 396
    MC_vars_i$GER_foraging <- ((P_cost + Es + Hg + P_nb + GERcalf_0to6m )/153)/E_FnU  #foraging pregnant = 153
    
    MC_vars_i$FR_foraging <- (MC_vars_i$GER_foraging / MC_vars_i$ED_prey) 
    MC_vars_i$pctbodywt <- (MC_vars_i$FR_foraging / MC_vars_i$mass)*100 
    
    #192 days foraging while preg, 134 days foraging while lact)
    MC_vars_i <- MC_vars_i %>% dplyr::mutate(ID = row_number())
    # move ID to the first column
    MC_vars_i<- MC_vars_i %>% dplyr::select(ID,everything()) 
    
    mean_GER_i <- mean(MC_vars_i$GER)
    sd_GER_i <- sd(MC_vars_i$GER)
    
    quant025 <- quantile(MC_vars_i$GER, 0.025, na.rm = TRUE)
    quant975 <- quantile(MC_vars_i$GER, 0.975, na.rm = TRUE)
    
    GER_foraging_i <- mean(MC_vars_i$GER_foraging)
    sd_foraging_i <- sd(MC_vars_i$GER_foraging)
    
    quant025_foraging <- quantile(MC_vars_i$GER_foraging, 0.025, na.rm = TRUE)
    quant975_foraging <- quantile(MC_vars_i$GER_foraging, 0.975, na.rm = TRUE)
    
    
    FR_foraging_i <- mean(MC_vars_i$FR_foraging)
    FR_sd_foraging_i <- sd(MC_vars_i$FR_foraging)
    
    FR_quant025_i <- quantile(MC_vars_i$FR_foraging, 0.025, na.rm = TRUE)
    FR_quant975_i <- quantile(MC_vars_i$FR_foraging, 0.975, na.rm = TRUE)
    
    pctbodywt <- mean(MC_vars_i$pctbodywt)
    pctbodywt_sd <- sd(MC_vars_i$pctbodywt)
    
    mean_Hg_i <- mean(Hg)
    sd_Hg_i <- sd(Hg)
    
    mass_i <- mean(MC_vars_i$mass)
    mass_sd_i <- sd(MC_vars_i$mass)
    
    P_nb_i <- mean(P_nb)
    GERcalf_0to6m_i <- mean(GERcalf_0to6m)
    
    MC_vars_i <- MC_vars_i %>%  dplyr::mutate(ID = row_number())
    MC_vars_i<- MC_vars_i %>%  dplyr::select(ID,everything()) # move ID to the first column
    
    
    row <- tibble(phase = phase,
                  age_yrs = age, 
                  MC_variable = MC_var,
                  mean_GER = mean_GER_i, 
                  GER_sd = sd_GER_i, 
                  quant025 = quant025, 
                  quant975 = quant975, 
                  GER_foraging = GER_foraging_i,
                  sd_foraging = sd_foraging_i, 
                  quant025_foraging = quant025_foraging,
                  quant975_foraging = quant975_foraging,
                  FR_foraging = FR_foraging_i,
                  FR_sd_foraging = FR_sd_foraging_i,
                  FR_quant025 = FR_quant025_i,
                  FR_quant975 = FR_quant975_i,
                  Hg = mean_Hg_i,
                  sd_Hg = sd_Hg_i,
                  P_nb = P_nb_i,
                  GERcalf_0to6m = GERcalf_0to6m_i,
                  mass = mass_i,
                  mass_sd = mass_sd_i,
                  pctbodywt = pctbodywt,
                  pctbodywt_sd = pctbodywt_sd
    )
    
    predict_GER_table_sensAnalysis_preg <- 
      rbind(predict_GER_table_sensAnalysis_preg, row)
    
  }
}


predict_GER_table_sensAnalysis_preg %>% 
  write_csv("data/predict_GER_table_sensAnalysis_preg.csv", 
            na = "", append = FALSE)


```

```{r plots_GER_preg}
predict_GER_table_sensAnalysis_preg <- read_csv("data/predict_GER_table_sensAnalysis_preg.csv")

plot_predict_GER_sensAnalysis_preg <- predict_GER_table_sensAnalysis_preg %>%
  filter(age_yrs<=30) %>% 
  ggplot() +
  geom_errorbar(aes(x = age_yrs, 
                    ymin = mean_GER - GER_sd, 
                    ymax = mean_GER + GER_sd), 
                width=0, linetype = 3,color="black") + 
  geom_point(aes(x = age_yrs, y= mean_GER), 
             shape = 21, fill = "white")+
  geom_errorbar(aes(x = age_yrs, 
                    ymin = GER_foraging - sd_foraging, 
                    ymax = GER_foraging + sd_foraging), 
                width=0, linetype = 3, color="black") + 
  geom_point(aes(x = age_yrs, y= GER_foraging), 
             shape = 21, fill = "black")+
  facet_grid(~MC_variable)+
  
  xlab("Age (years)") +
  ylab(bquote('GER (MJ day '^'-1'*')')) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10), 
                     limits = c(8, 30)) +  # max x-axis 30 yrs. 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 8),
                     labels = comma
                     #limits = c(0,max(plot_predict_GER_sensAnalysis_preg$quant975_foraging))
  ) +
  theme_bw() +
  theme(panel.grid = element_blank())+
  theme(strip.background =element_rect(fill="transparent",
                                       colour = "transparent"))+
  theme(strip.text = element_text(size = rel(1)))


plot_predict_GER_sensAnalysis_preg              


```



```{r GER_lact}

predict_GER_table_sensAnalysis_lact <- 
  as.data.frame(matrix(ncol = 20, nrow = 0))

cnames <- c("phase","age_yrs", "MC_variable", 
            "mean_GER", "GER_sd", 
            "quant025", "quant975", 
            "GER_foraging", "sd_foraging",
            "quant025_foraging", "quant975_foraging",   #2.5% and 97.5% quantile from bootstrap estimates
            "FR_foraging", "FR_sd_foraging",
            "FR_quant025","FR_quant975",
            "GERcalf_7to9m", 
             "mass","mass_sd", "pctbodywt", "pctbodywt_sd"
)            

colnames(predict_GER_table_sensAnalysis_lact) <- cnames

predict_GER_table_sensAnalysis_lact <- as_tibble(
  predict_GER_table_sensAnalysis_lact,
  col_types = (list(ID = col_integer(),
                    phase = col_character(),
                    age_yrs = col_double(), 
                    MC_variable = col_character(),
                    mean_GER = col_double(), 
                    GER_sd = col_double(), 
                    quant025 = col_double(), 
                    quant975 = col_double(), 
                    GER_foraging = col_double(),
                    sd_foraging = col_double(), 
                    quant025_foraging = col_double(),
                    quant975_foraging = col_double(),
                    FR_foraging = col_double(),
                    FR_sd_foraging = col_double(),
                    FR_quant025 = col_double(),
                    FR_quant975 = col_double(),
                    GERcalf_7to9m = col_double(),
                    mass = col_double(),
                    mass_sd = col_double(),
                    pctbodywt = col_double(),
                    pctbodywt_sd = col_double()
  )
  )
)




for (i in seq(from = 8, to = 74, by = 1)){
  for (MC_var in c("all","P_cost","Es","GERcalf","E_FnU")){
    
    age <-  i
    s <- "Female"
    phase <- "Lactating"
    
    
    mass <- mass_table %>% 
      dplyr::filter(age_yrs == age) %>% 
      dplyr::select(mean_mass) %>% 
      pull(mean_mass)
    
    if (MC_var == "all"){
      mass_sd <- mass_table %>% 
        dplyr::filter(age_yrs == age) %>% 
        dplyr::select(sd_mass) %>% 
        pull(sd_mass)
    } else {
      mass_sd <-0
    }
    
    # Production cost values
    P_cost_i <- P_cost_table_lact %>% 
      dplyr::filter(P_cost_table_lact$age_yrs == age)  
    P_cost_i <- P_cost_i %>% 
      dplyr::filter(P_cost_i$sex == s) 
    
    # no of days
    Ts <- P_cost_i$Ts
    
    mean_P <- P_cost_i$mean_P
    
    if (MC_var == "all" || MC_var == "P_cost"){
      sd_P <-  P_cost_i$sd_P
    } else {
      sd_P <- 0
    }
    
    # Energy expenditure values
    Es_table_i <- Es_lact_table %>% 
      dplyr::filter(Es_lact_table$age_yrs == age & 
                      Lifestage == "Lactating") 
    Es <- Es_table_i$Es
    
    if (MC_var == "all" || MC_var == "Es"){
      Es_sd <- Es_table_i$Es_sd
    } else {
      Es_sd <- 0
    }
    
    #Fecal and Urinary cost - E_FnU
    E_FnU_min = 0.740
    E_FnU_max = 0.858
    E_FnU_mean = (E_FnU_min + E_FnU_max)/2
    
    #Energetic density of Prey - ED_prey
    ED_prey_mean = 2.90 #MJ/kg  from average I calculated... 
    ED_prey_min = 2.51   #from Coyle et al. 2007
    ED_prey_max = 3.41   #from Stoker 1978
    
    if (MC_var == "all"){
      ED_prey_sd = 0.0408  #calculated from table 3  
    } else {
      ED_prey_sd = 0
    }
    
    
    # GER Calf 7 to 9.6 (nursing)
    GERcalf7to9.6mths_tibble <-  TotalGER_birth_to_weaning_tibble %>% 
      filter(age_range == "7 to 9.6 mths") 
    GERcalf7to9.6mths <- GERcalf7to9.6mths_tibble$Total_GER
    
    if (MC_var == "all" || MC_var == "GERcalf"){
      GERcalf7to9.6mths_sd <- GERcalf7to9.6mths_tibble$Total_GER_sd
    } else {
      GERcalf7to9.6mths_sd <- 0
    }
    
    
    # Monte carlo - Production cost
    set.seed(12345)
    MC_vars_i <- as_tibble(rnorm(MC_reps, mean_P, sd_P))
    names(MC_vars_i)[1] <- "P_cost"
    
    MC_vars_i$sex <- s   # do i need to identify sex here?
    MC_vars_i$GER <- NA
    MC_vars_i<- MC_vars_i %>%  
      dplyr::select(sex, GER, everything()) #move sex to the first column
    
    # Monte carlo - Es
    set.seed(12345)
    Es_i <-  as_tibble(rnorm(MC_reps, Es, Es_sd))
    names(Es_i)[1] <- "Es"
    
    MC_vars_i <- cbind(MC_vars_i, Es_i)
    
    # Monte carlo - Fecal and urinary waste - E_FnU
    set.seed(12345)
    if (MC_var == "E_FnU" || MC_var == "all"){
      E_FnU_i <- as_tibble(runif(MC_reps, min = E_FnU_min, max = E_FnU_max)) 
    } else {
      E_FnU_i <- as_tibble(runif(MC_reps, min = E_FnU_mean, max = E_FnU_mean)) 
    }
    names(E_FnU_i)[1] <- "E_FnU"
    
    MC_vars_i <- cbind(MC_vars_i, E_FnU_i)
    
    # Monte carlo - ED_prey
    ED_prey_i <- as_tibble(rnorm(MC_reps, ED_prey_mean, ED_prey_sd))
    names(ED_prey_i)[1] <- "ED_prey"
    
    MC_vars_i <- cbind(MC_vars_i, ED_prey_i)
    
    # Monte Carlo - mass (for pct body wt calcs)
    set.seed(12345)
    mass_i <- as_tibble(rnorm(MC_reps, mass , mass_sd))
    names(mass_i)[1] <- "mass"
    
    MC_vars_i <- cbind(MC_vars_i, mass_i)

    # Monte carlo - GER Calf - 7 to 9.6 mths (nursing)
    GERcalf7to9.6mths_tibble <- as_tibble(rnorm(MC_reps, GERcalf7to9.6mths, GERcalf7to9.6mths_sd))
    #names(GERcalf7to9.6mths)[1] <- "GERcalf7to9.6mths"
    GERcalf7to9.6mths_tibble <- GERcalf7to9.6mths_tibble %>% rename("GERcalf7to9.6mths_tibble"="value")
    
    MC_vars_i <- cbind(MC_vars_i, GERcalf7to9.6mths)
    
    # Pcostof mother
    P_cost <- MC_vars_i$P_cost 
    Es <- MC_vars_i$Es
    E_FnU <- MC_vars_i$E_FnU
    GERcalf7to9.6mths <- MC_vars_i$GERcalf7to9.6mths
    
    #GER   Es - includes digestion, maintenance and activity
    MC_vars_i$GER <- ((P_cost + Es + GERcalf7to9.6mths)/365)/(E_FnU) 
    # 293 days total nursing in one cycle plus postweaning travel days = 365
    MC_vars_i$GER_foraging <- ((P_cost + Es + GERcalf7to9.6mths)/119)/(E_FnU)  
    # 119 days foraging while lactating
    
    
    MC_vars_i$FR_foraging <- (MC_vars_i$GER_foraging / MC_vars_i$ED_prey) 
    MC_vars_i$pctbodywt <- (MC_vars_i$FR_foraging / MC_vars_i$mass)*100 
    
    MC_vars_i <- MC_vars_i %>%  dplyr::mutate(ID = row_number())
    MC_vars_i<- MC_vars_i %>%  
      dplyr::select(ID,everything()) # move ID to the first column
    
    mean_GER_i <- mean(MC_vars_i$GER)
    sd_GER_i <- sd(MC_vars_i$GER)
    
    quant025 <- quantile(MC_vars_i$GER, 0.025, na.rm = TRUE)
    quant975 <- quantile(MC_vars_i$GER, 0.975, na.rm = TRUE)
    
    GER_foraging_i <- mean(MC_vars_i$GER_foraging)
    sd_foraging_i <- sd(MC_vars_i$GER_foraging)
    
    quant025_foraging <- quantile(MC_vars_i$GER_foraging, 0.025, na.rm = TRUE)
    quant975_foraging <- quantile(MC_vars_i$GER_foraging, 0.975, na.rm = TRUE)
    
    
    FR_foraging_i <- mean(MC_vars_i$FR_foraging)
    FR_sd_foraging_i <- sd(MC_vars_i$FR_foraging)
    
    FR_quant025_i <- quantile(MC_vars_i$FR_foraging, 0.025, na.rm = TRUE)
    FR_quant975_i <- quantile(MC_vars_i$FR_foraging, 0.975, na.rm = TRUE)
    
    pctbodywt <- mean(MC_vars_i$pctbodywt)
    pctbodywt_sd <- sd(MC_vars_i$pctbodywt)
    
    
    GERcalf7to9.6mths_i <- mean(GERcalf7to9.6mths)
    
    
    MC_vars_i <- MC_vars_i %>%  dplyr::mutate(ID = row_number())
    MC_vars_i<- MC_vars_i %>% 
      dplyr::select(ID,everything()) # move ID to the first column
    
    
    newrow <- tibble(phase = phase, 
                  age_yrs = age, 
                  MC_variable = MC_var,
                  mean_GER = mean_GER_i, 
                  GER_sd = sd_GER_i, 
                  quant025 = quant025, 
                  quant975 = quant975, 
                  GER_foraging = GER_foraging_i,
                  sd_foraging = sd_foraging_i, 
                  quant025_foraging = quant025_foraging,
                  quant975_foraging = quant975_foraging,
                  FR_foraging = FR_foraging_i,
                  FR_sd_foraging = FR_sd_foraging_i,
                  FR_quant025 = FR_quant025_i,
                  FR_quant975 = FR_quant975_i,
                  GERcalf7to9.6mths = GERcalf7to9.6mths_i,
                  mass = mass,
                  mass_sd = mass_sd,
                  pctbodywt = pctbodywt,
                  pctbodywt_sd = pctbodywt_sd
    )
    
    predict_GER_table_sensAnalysis_lact <- 
      rbind(predict_GER_table_sensAnalysis_lact, newrow)
    
  }
}



predict_GER_table_sensAnalysis_lact %>% write_csv("data/predict_GER_table_sensAnalysis_lact.csv", na = "", append = FALSE)


```

```{r plots_GER_lact}

predict_GER_table_sensAnalysis_lact <- read_csv("data/predict_GER_table_sensAnalysis_lact.csv")

plot_predict_GER_table_sensAnalysis_lact <- predict_GER_table_sensAnalysis_lact %>%
  filter(age_yrs<=30) %>% 
  ggplot() +
  geom_errorbar(aes(x = age_yrs, 
                    ymin = mean_GER - GER_sd, 
                    ymax = mean_GER + GER_sd), 
                width=0, linetype = 3,color="gray40") + 
  geom_point(aes(x = age_yrs, y= mean_GER), 
             shape = 21, fill = "white")+
  geom_errorbar(aes(x = age_yrs, 
                    ymin = GER_foraging - sd_foraging, 
                    ymax = GER_foraging + sd_foraging), 
                width=0, linetype = 3, color="gray40") + 
  geom_point(aes(x = age_yrs, y= GER_foraging), 
             shape = 21, fill = "black")+
  facet_grid(~MC_variable)+
xlab("Age (years)") +
  ylab(bquote('GER (MJ day '^'-1'*')')) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 5), 
                     limits = c(8, 30)) +  # max x-axis 30 yrs. 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 8)
                     #limits = c(0, max(predict_GER_table_lact$quant975_foraging))
  ) +
  theme_bw() +
  theme(panel.grid = element_blank())


plot_predict_GER_table_sensAnalysis_lact

```



