---
title: "Total Gross Energy Requirements for calves from birth to weaning"
author: "Selina Agbayani"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output:
  github_document:
  html_document:
  pdf_document:
    
editor_options:
  chunk_output_type: console
classoption: landscape
---



```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(error = TRUE)
#quiet col types messages
options(readr.show_col_types = FALSE)
## Setup

# Initialize all libraries, set paths for output figures, then import the gw_observations.csv
# install.packages("tidyr")
# install.packages("readr")
# install.packages("tidyverse")
# install.packages("dplyr")
# install.packages("ggplot2")
# install.packages("knitr")
# install.packages("nls2")
# install.packages("nlstools")
# install.packages("nlme")
# install.packages("minpack.lm")
# install.packages("scales")
# install.packages("ggpmisc")
# install.packages("extrafont")
# install.packages("gtable")
# install.packages("ggpubr")

library(tidyverse)
library(tidyr)
library(readr)
library(dplyr)
library(ggplot2)
library(knitr)
library(nls2)
library(nlstools)
library(nlme)
library(minpack.lm)
library(scales)
library(ggpmisc)
library(reshape2)
library(extrafont)
library(gtable)
library(ggpubr)

#source("functions.R")

 
```


```{r declare functions and global variables, include=FALSE}

# **Declare custom functions and global variables**
########## Specify Decimal function ############################
# 
# For use in labelling the plots with equations, and rounding up the coefficients
# to a specific no. of decimal places
specify_decimal <- function(x, k) format(round(x, k), nsmall=k)


############ Multiple plot function######################
#
# ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
# - cols:   Number of columns in layout
# - layout: A matrix specifying the layout. If present, 'cols' is ignored.
#
# If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
# then plot 1 will go in the upper left, 2 will go in the upper right, and
# 3 will go all the way across the bottom.
#
# Code extracted from Cookbook for R. This site is powered by knitr and Jekyll. 
# If you find any errors, please email winston@stdout.org

multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}


########### functions used for carry out the fit ########

## this function is avaible in: 
# http://www.leg.ufpr.br/~walmes/cursoR/ciaeear/as.lm.R   or in 
# https://gist.github.com/TonyLadson/2d63ca70eef92583001dece607127759 (from the line 269)

##### as.lm function: ######

        as.lm <- function(object, ...) UseMethod("as.lm")

        as.lm.nls <- function(object, ...) {
            if (!inherits(object, "nls")) {
                w <- paste("expected object of class nls but got object of class:", 
                    paste(class(object), collapse = " "))
                warning(w)
            }

            gradient <- object$m$gradient()
            if (is.null(colnames(gradient))) {
                colnames(gradient) <- names(object$m$getPars())
            }

            response.name <- if (length(formula(object)) == 2) "0" else 
                as.character(formula(object)[[2]])

            lhs <- object$m$lhs()
            L <- data.frame(lhs, gradient)
            names(L)[1] <- response.name

            fo <- sprintf("%s ~ %s - 1", response.name, 
                paste(colnames(gradient), collapse = "+"))
            fo <- as.formula(fo, env = as.proto.list(L))

            do.call("lm", list(fo, offset = substitute(fitted(object))))

        }

############## End as.lm function 



############### proto function: ############
#### proto function avaible in https://github.com/hadley/proto/blob/master/R/proto.R

proto <- function(. = parent.env(envir), expr = {},
                   envir = new.env(parent = parent.frame()), ...,
                   funEnvir = envir) {
  parent.env(envir) <- .
  envir <- as.proto.environment(envir)  # must do this before eval(...)
  # moved eval after for so that ... always done first
  # eval(substitute(eval(quote({ expr }))), envir)
  dots <- list(...); names <- names(dots)
  for (i in seq_along(dots)) {
    assign(names[i], dots[[i]], envir = envir)
    if (!identical(funEnvir, FALSE) && is.function(dots[[i]]))
      environment(envir[[names[i]]]) <- funEnvir
  }
  eval(substitute(eval(quote({
    expr
  }))), envir)
  if (length(dots))
    as.proto.environment(envir)
  else
    envir
}

#' @export
#' @rdname proto
as.proto <- function(x, ...) {
  UseMethod("as.proto")
}

#' @export
#' @rdname proto
as.proto.environment <- function(x, ...) {
  assign(".that", x, envir = x)
  assign(".super", parent.env(x), envir = x)
  structure(x, class = c("proto", "environment"))
}

#' @export
#' @rdname proto
as.proto.proto <- function(x, ...) {
  x
}
as.proto.list <- function(x, envir, parent, all.names = FALSE, ...,
                          funEnvir = envir, SELECT = function(x) TRUE) {
  if (missing(envir)) {
    if (missing(parent))
      parent <- parent.frame()
    envir <- if (is.proto(parent))
      parent$proto(...)
    else
      proto(parent, ...)
  }
  for (s in names(x))
    if (SELECT(x[[s]])) {
      assign(s, x[[s]], envir = envir)
      if (is.function(x[[s]]) && !identical(funEnvir, FALSE))
        environment(envir[[s]]) <- funEnvir
    }
  if (!missing(parent))
    parent.env(envir) <- parent
  as.proto.environment(envir)  # force refresh of .that and .super
}

#' @export
"$<-.proto" <- function(this,s,value) {
  if (s == ".super")
    parent.env(this) <- value
  if (is.function(value))
    environment(value) <- this
  this[[as.character(substitute(s))]] <- value
  this
}
is.proto <- function(x) inherits(x, "proto")

#' @export
"$.proto" <- function(x, name) {
  inherits <- substr(name, 1, 2) != ".."

  res <- get(name, envir = x, inherits = inherits)
  if (!is.function(res))
    return(res)

  if (deparse(substitute(x)) %in% c(".that", ".super"))
    return(res)

  structure(
    function(...) res(x, ...),
    class = "protoMethod",
    method = res
  )
}

#' @export
print.protoMethod <- function(x, ...) {
  cat("<ProtoMethod>\n")
  print(attr(x, "method"), ...)
}

# modified from Tom Short's original
#' @export
str.proto <- function(object, max.level = 1, nest.lev = 0,
                      indent.str = paste(rep.int(" ", max(0, nest.lev + 1)), collapse = ".."),
                      ...) {
  cat("proto", name.proto(object), "\n")
  Lines <- utils::capture.output(utils::str(
    as.list(object), max.level = max.level,
    nest.lev = nest.lev, ...
  ))[-1]
  for (s in Lines)
    cat(s, "\n")
  if (is.proto(parent.env(object))) {
    cat(indent.str, "parent: ", sep = "")
    utils::str(parent.env(object), nest.lev = nest.lev + 1, ...)
  }
}

#' @export
print.proto <- function(x, ...) {
  if (!exists("proto_print", envir = x, inherits = TRUE))
    return(NextMethod())

  x$proto_print(...)
}

############# End proto function 

############ PredictNLS - for confidence intervals  ##########
# Source: https://rmazing.wordpress.com/2013/08/14/predictnls-part-1-monte-carlo-simulation-confidence-intervals-for-nls-models/

predictNLS <- function(object,newdata,level = 0.95, nsim = 10000,
                       ...){
    require(MASS, quietly = TRUE)
    ## get right-hand side of formula
    RHS <- as.list(object$call$formula)[[3]]
    EXPR <- as.expression(RHS)
   
    ## all variables in model
    VARS <- all.vars(EXPR)
   
    ## coefficients
    COEF <- coef(object)
   
    ## extract predictor variable    
    predNAME <- setdiff(VARS, names(COEF))  
   
    ## take fitted values, if 'newdata' is missing
    if (missing(newdata)) {
        newdata <- eval(object$data)[predNAME]
        colnames(newdata) <- predNAME
        }
       
    ## check that 'newdata' has same name as predVAR
    if (names(newdata)[1] != predNAME) stop("newdata should have name '",
                                            predNAME, "'!")
   
    ## get parameter coefficients
    COEF <- coef(object)
     
    ## get variance-covariance matrix
    VCOV <- vcov(object)
   
    ## augment variance-covariance matrix for 'mvrnorm' 
    ## by adding a column/row for 'error in x'
    NCOL <- ncol(VCOV)
    ADD1 <- c(rep(0, NCOL))
    ADD1 <- matrix(ADD1, ncol = 1)
    colnames(ADD1) <- predNAME
    VCOV <- cbind(VCOV, ADD1)
    ADD2 <- c(rep(0, NCOL + 1))
    ADD2 <- matrix(ADD2, nrow = 1)
    rownames(ADD2) <- predNAME
    VCOV <- rbind(VCOV, ADD2) 
         
    ## iterate over all entries in 'newdata' as in usual 'predict.' functions
    NR <- nrow(newdata)
    respVEC <- numeric(NR)
    seVEC <- numeric(NR)
    varPLACE <- ncol(VCOV)   
   
    ## define counter function
    counter <- function (i) {
        if (i%%10 == 0) 
            cat(i)
        else cat(".")
        if (i%%50 == 0) 
            cat("\n")
        flush.console()
        }
   
    outMAT <- NULL 
   
    for (i in 1:NR) {
        counter(i)
        ## get predictor values and optional errors
    predVAL <- newdata[i, 1]
    if (ncol(newdata) == 2) predERROR <- newdata[i, 2] else predERROR <- 0
    names(predVAL) <- predNAME  
    names(predERROR) <- predNAME  
     
    ## create mean vector for 'mvrnorm'
    MU <- c(COEF, predVAL)
     
    ## create variance-covariance matrix for 'mvrnorm'
    ## by putting error^2 in lower-right position of VCOV
    newVCOV <- VCOV
    newVCOV[varPLACE, varPLACE] <- predERROR^2
     
    ## create MC simulation matrix
    simMAT <- mvrnorm(n = nsim, mu = MU, Sigma = newVCOV, empirical = TRUE)
     
    ## evaluate expression on rows of simMAT
    EVAL <- try(eval(EXPR, envir = as.data.frame(simMAT)), silent = TRUE)
    if (inherits(EVAL, "try-error")) stop("There was an error evaluating the simulations!")
     
    ## collect statistics
    PRED <- data.frame(predVAL)
    colnames(PRED) <- predNAME   
    FITTED <- predict(object, newdata = data.frame(PRED))
    MEAN.sim <- mean(EVAL, na.rm = TRUE)
    SD.sim <- sd(EVAL, na.rm = TRUE)
    MEDIAN.sim <- median(EVAL, na.rm = TRUE)
    MAD.sim <- mad(EVAL, na.rm = TRUE)  #median absolute deviation
    QUANT <- quantile(EVAL, c((1 - level)/2, level + (1 - level)/2))
    RES <- c(FITTED, MEAN.sim, SD.sim, MEDIAN.sim, MAD.sim, QUANT[1], QUANT[2])
    outMAT <- rbind(outMAT, RES)
  }
   
  colnames(outMAT) <- c("fit", "mean", "sd", "median", "mad", names(QUANT[1]), names(QUANT[2]))
  rownames(outMAT) <- NULL
   
  cat("\n")
   
  return(outMAT)  
}

##########end PredictNLS ##########

        
```   



```{r setpaths}       
# Set path for output figures: 
Figurespath <- paste0(getwd(), "/gross_energetic_reqs/figures", collapse = NULL)
Figurespath

# Set path for input & output data  
datapath <- paste0(getwd(), "/data", collapse = NULL) 
datapath

```

```{r read in data}

#read in GER phase 1 table to calculate total GER from birth to weaning 
predict_GER_table_phase1_permth<- read_csv("data/predict_GER_table_sensAnalysis_phase1_permth_source_bpm.csv")
predict_GER_table_phase1_permth <-  predict_GER_table_phase1_permth %>% filter(age_mth <= 10 & MC_variable == "all" & sex == "N/A") %>% 
   select(phase, age_yrs,age_mth, sex, mean_GER, GER_sd, Ts)



```


Calculating total GER from birth to 6mths, and from 7mth-9.6mth, and also from birth to 9.6 mth

```{r GER_birth_to_weaning}

#Calculate total GER from birth to end of fasting (at 6 mths)  
predict_GER_0to6mth <-  predict_GER_table_phase1_permth %>% filter(age_mth <= 6)

predict_GER_0to6mth$GER_mth <- predict_GER_0to6mth$mean_GER * predict_GER_0to6mth$Ts

predict_GER_0to6mth$GER_sd_sqrd <- predict_GER_0to6mth$GER_sd ^2
kable(predict_GER_0to6mth)

TotalGER_0to6mth_tibble <- predict_GER_0to6mth %>%
  select(age_yrs, sex, mean_GER, GER_mth, GER_sd, GER_sd_sqrd) %>%
  group_by(sex) %>%
  summarize(Total_GER = sum(GER_mth), Total_GER_sd = sqrt(sum(GER_sd_sqrd)))


TotalGER_0to6mth_tibble$age_range <- "0 to 6 mths"
TotalGER_0to6mth_tibble  <-  TotalGER_0to6mth_tibble %>% relocate(age_range)
TotalGER_0to6mth_tibble$details <- "birth to end of nursing mother fasting"

kable(TotalGER_0to6mth_tibble)

GERcalf6mths_tibble  <-  TotalGER_0to6mth_tibble %>% filter(sex == "N/A")
GERcalf_6mths <- GERcalf6mths_tibble$Total_GER
GERcalf_6mths_sd <- GERcalf6mths_tibble$Total_GER_sd


#Calculating GER till weaning at 9.6 months

#need to adjust October to 20 days worth of GER because weaning is at 9.6 mths.
mean_GER_10th <- predict_GER_table_phase1_permth %>% 
  filter(age_mth == 10) %>% 
  pull(mean_GER)

Ts_9.6 <- 20 #nursing for 20 days out of 31 days in Oct

mean_GER_9.6 <- mean_GER_10th * (20/31) 

sd_GER_9.6 <- predict_GER_table_phase1_permth %>%  
  filter(age_mth == 10) %>%  
  pull(GER_sd)*(20/31)

sd_GER_9.6_sqrd <-sd_GER_9.6^2

Oct_row <- tibble(phase = "1",
              age_yrs = (9.6/12),
              age_mth = 9 + (20/31),
              sex = "N/A",
              mean_GER = mean_GER_9.6,
              GER_sd = sd_GER_9.6,
              Ts = Ts_9.6,
              GER_mth = mean_GER_9.6*Ts_9.6,
              GER_sd_sqrd = sd_GER_9.6_sqrd
)


#Total GER for calf from start of Mother foraging while lactating (7 mths) to weaning (9.6 mths) 
predict_GER_7to9mth <-  predict_GER_table_phase1_permth %>% 
  filter(age_mth >= 7 & age_mth <=9) %>%
  select(phase, age_yrs, age_mth, sex, mean_GER, GER_sd, Ts)

predict_GER_7to9mth$GER_mth <- predict_GER_7to9mth$mean_GER * predict_GER_7to9mth$Ts

predict_GER_7to9mth$GER_sd_sqrd <- predict_GER_7to9mth$GER_sd ^2
kable(predict_GER_7to9mth)

predict_GER_7to9.6mth <- rbind(predict_GER_7to9mth, Oct_row)

TotalGER_7to9.6mth_tibble <- predict_GER_7to9.6mth %>%
  select(age_yrs, sex, mean_GER, GER_mth, GER_sd, GER_sd_sqrd) %>%
  group_by(sex) %>%
  summarize(Total_GER = sum(GER_mth), Total_GER_sd = sqrt(sum(GER_sd_sqrd)))

TotalGER_7to9.6mth_tibble$age_range <- "7 to 9.6 mths"
TotalGER_7to9.6mth_tibble  <-  TotalGER_7to9.6mth_tibble %>% relocate(age_range)
TotalGER_7to9.6mth_tibble$details <- "start of nursing mother foraging to weaning"

kable(TotalGER_7to9.6mth_tibble)

TotalGER_for0to6_7to9.6_tibble <- rbind(TotalGER_0to6mth_tibble,TotalGER_7to9.6mth_tibble)

kable(TotalGER_for0to6_7to9.6_tibble)


#Total GER for calf from birth to weaning (9.6 mths) 
predict_GER_0to9mth <-  predict_GER_table_phase1_permth %>% 
  filter(age_mth >= 0 & age_mth <=9) %>%
  select(phase, age_yrs, age_mth, sex, mean_GER, GER_sd, Ts)

predict_GER_0to9mth$GER_mth <- predict_GER_0to9mth$mean_GER * predict_GER_0to9mth$Ts

predict_GER_0to9mth$GER_sd_sqrd <- predict_GER_0to9mth$GER_sd ^2
kable(predict_GER_0to9mth)

predict_GER_0to9.6mth <- rbind(predict_GER_0to9mth, Oct_row)

TotalGER_0to9.6mth_tibble <- predict_GER_0to9.6mth %>%
  select(age_yrs, sex, mean_GER, GER_mth, GER_sd, GER_sd_sqrd) %>%
  group_by(sex) %>%
  summarize(Total_GER = sum(GER_mth), Total_GER_sd = sqrt(sum(GER_sd_sqrd)))

TotalGER_0to9.6mth_tibble$age_range <- "0 to 9.6 mths"
TotalGER_0to9.6mth_tibble  <-  TotalGER_0to9.6mth_tibble %>% relocate(age_range)
TotalGER_0to9.6mth_tibble$details <- "birth to weaning"

kable(TotalGER_0to9.6mth_tibble)

TotalGER_birth_to_weaning_tibble <- rbind(TotalGER_0to6mth_tibble,
                                          TotalGER_7to9.6mth_tibble,
                                          TotalGER_0to9.6mth_tibble )

kable(TotalGER_birth_to_weaning_tibble)


TotalGER_birth_to_weaning_tibble %>% write_csv("data/TotalGER_birth_to_weaning_tibble.csv", na = "", append = FALSE)

```


**Total GER from birth to weaning, taking into account foraging time for nursing mother.**

```{r plot, echo=FALSE}

TotalGER_birth_to_weaning_tibble <-  read_csv("data/TotalGER_birth_to_weaning_tibble.csv")
TotalGER_birth_to_weaning_plot <- TotalGER_birth_to_weaning_tibble %>% 
  ggplot()+
  geom_errorbar(aes(x = age_range, 
                    ymin = Total_GER - Total_GER_sd, 
                    ymax = Total_GER + Total_GER_sd), 
                width=0, linetype = 1,color="black") + 
  # geom_point(aes(x = age_range, y= Total_GER),
  #            shape = 21, size = 5) +
    geom_bar(aes(x = age_range, y= Total_GER),
             stat = "identity", fill = "gray80") +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 8),
                     labels = comma)+
  xlab("Age range (months)") +
  ylab(bquote('Gross Energetic Requirement (MJ)')) +
  theme_bw() 
  #theme(panel.grid = element_blank())
  

TotalGER_birth_to_weaning_plot


```



