---
title: "Mass change needed to calculate cost of lactation"
author: "Selina Agbayani"
date: "Feb 11, 2021, updated and cleaned `r format(Sys.time(), '%d %B, %Y')`"
output:
  github_document:
  html_document:

editor_options: 
  chunk_output_type: console
---



```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(error = TRUE)


## Setup

# Initialize all libraries, set paths for output figures, then import the gw_observations.csv
# install.packages("tidyr")
# install.packages("tidyverse")
# install.packages("dplyr")
# install.packages("ggplot2")
# install.packages("knitr")
# install.packages("nls2")
# install.packages("nlstools")
# install.packages("nlme")
# install.packages("minpack.lm")
# install.packages("scales")
# install.packages("ggpmisc")
# install.packages("extrafont")


library(tidyr)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(knitr)
library(nls2)
library(nlstools)
library(nlme)
library(minpack.lm)
library(scales)
library(ggpmisc)
library(reshape2)
library(extrafont)


# #quiet col types messages
# options(readr.show_col_types = FALSE)


```



```{r functions, include=FALSE}

source("../functions.R", local = knitr::knit_global())

```   

```{r set output paths}       
############ Set path for output figures: ###############
Figurespath <- paste0(getwd(), "/delta_mass/figures", collapse = NULL)
Figurespath
############ Set path for input & output data  ###########
datapath <-  paste0(getwd(), "/data", collapse = NULL) 
datapath

```



```{r read data in}
## Read data in

mass_table <- as_tibble(read_csv("data/mass_table.csv"), #monthly 
                                 col_types = (list(cols(age_yrs = col_double(),
                                                        mean_mass = col_double(),
                                                        sd_mass = col_double(),
                                                        mean_lwr = col_double(),
                                                        mean_upr = col_double(),
                                                        quant025 = col_double(),
                                                        quant975 = col_double(),
                                                        female_mass = col_double(),
                                                        male_mass = col_double()
                                                        )
                                                   )
                                              )
                                 )


mass_at_birth_tibble <- mass_table %>% filter(age_yrs == 0)  #at birth

mass_at_birth_mean <- mass_at_birth_tibble$mean_mass 
mass_at_birth_sd <- mass_at_birth_tibble$sd_mass


mass_at_weaning_tibble <- mass_table %>%  filter(round(age_yrs,2) == round((10/12),2))  #10th mth  i.e. 0.8333333

mass_at_weaning_mean <-mass_at_weaning_tibble$mean_mass 
mass_at_weaning_sd <-mass_at_weaning_tibble$sd_mass


```

The mass change needed to calculate cost of lactation is the increase 
in mass from newborn to weaning. 

```{r mean cost of lactation}

MC_reps = 10000

mass_at_birth_reps <- rnorm(MC_reps, mass_at_birth_mean, mass_at_birth_sd)
mass_at_weaning_reps <- rnorm(MC_reps, mass_at_weaning_mean, mass_at_weaning_sd)

mass_change_lactation_reps <- mass_at_weaning_reps - mass_at_birth_reps

masschange_lactation_mean <- mean(mass_change_lactation_reps)
masschange_lactation_sd <- sd(mass_change_lactation_reps)

masschange_lactation_mean
masschange_lactation_sd


```

Mean mass change: `r masschange_lactation_mean`.

Sd mass change: `r masschange_lactation_sd`.


