---
title: "Es - Total metabolic energy expenditure at a given stage - source bpm version - Phase 1"
author: "S. Agbayani"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  github_document:
  html_document:
  pdf_document:
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(error = TRUE)

## Setup

# Initialize all libraries, set paths for output figures, then import the gw_observations.csv
# install.packages("tidyr")
# install.packages("tidyverse")
# install.packages("dplyr")
# install.packages("ggplot2")
# install.packages("knitr")
# install.packages("nls2")
# install.packages("nlstools")
# install.packages("nlme")
# install.packages("minpack.lm")
# install.packages("scales")
# install.packages("ggpmisc")
# install.packages("extrafont")
#install.packages("truncnorm")



library(tidyverse)
# library(tidyr)
# library(dplyr)
# library(ggplot2)
library(knitr)
library(nls2)
library(nlstools)
library(nlme)
library(minpack.lm)
library(scales)
library(ggpmisc)
library(reshape2)
library(extrafont)
library(truncnorm)

source("functions.R")

```

```{r setpaths}
############ Set path for output figures: ###############
Figurespath <- paste0(getwd(), "/FMR/figures", collapse = NULL)
Figurespath
############ Set path for input & output data  ###########
datapath <- paste0(getwd(), "/data", collapse = NULL) 
datapath




```

```{r readindata}
# Read in Tidal Volume table - Vt
Vt_table_phase1 <- as_tibble(read_csv("data/Vt_table_phase1.csv"), 
                             col_types = (list(cols(age_yrs = col_double(),
                                                    Vt_mean = col_double(),
                                                    Vt_sd = col_double(),
                                                    quant025 = col_double(),
                                                    quant975 = col_double()
                             )
                             )
                             )
)


# Read in Activity Cost Reference data from csv  ORIGINAL SOURCE VALUES
A_cost_reference <- as_tibble(
  read_csv("data/ActivityCost_ReferenceData_BreathsPerDay_Table_VA_2017_original_sources.csv"),
  col_types = (list(cols(  ID = col_double(),
                           Lifestage = col_character(),
                           Description = col_character(),
                           Activity_stages = col_character(),
                           no_days = col_double(),
                           source_no_days = col_character(),
                           bpm = col_double(),
                           se_bpm = col_double(),
                           source_bpm = col_character(),
                           age_yrs = col_double(),
                           age_yrs_min = col_double(),
                           age_yrs_max = col_double(),
                           pct_O2 = col_double(),
                           pct_O2_sd = col_double()
  )
  )
  )
)

kable(A_cost_reference)

age_yr_tibble <- as_tibble(
  read_csv("data/age_yr_tibble.csv"), 
  col_types = (list(ID = col_integer(),
                    month = col_character(),
                    no_days_in_mth = col_double(),
                    age_mth = col_double(),
                    no_days_cumul = col_double(),
                    age_yrs = col_double()
  )
  )
)



```

Es - Total metabolic energy expenditure at a given stage 0.02 - Amount of heat produced in MJ/L O2 consumed (Kleiber 1961)  
%O2 - Extraction efficiency per breath Ts - The no. of days in that stage Rs - Respiration rate (breaths/day) Vt - Tidal lung volume (L)

------------------------------------------------------------------------

Es = 0.02 x %O2 x Ts x Rs x Vt - Sumich (1986)

```{r Es_phase1}

Lifestage <-  "Calf"

A_cost_reference_calf <- A_cost_reference %>% filter(Lifestage == "Calf")

A_cost_calf <-  A_cost_reference_calf %>%
  dplyr::select(Lifestage, Activity_stages, age_yrs, no_days, bpm, se_bpm) %>%
  filter(Lifestage == "Calf")  

# for (i in seq(from = 1, to = 12, by = 1)){
#   
#     age <- age_yr_tibble %>% dplyr::filter(age_mth == i) %>%  pull(age_yrs)  
#     age_yrs <- A_cost_calf$age_yrs
#     A_cost_tibble <- A_cost_calf %>% dplyr::filter(round(age_yrs,3) == round(age,3))
#     act <- A_cost_tibble$Activity_stages
#     no_days_i <- sum(A_cost_tibble$no_days)
#     bpm_i <- A_cost_tibble$bpm
#     se_bpm_i <- A_cost_tibble$se_bpm
#     
#     
#     row <- tibble(Lifestage = Lifestage,
#                   Activity_stages = act,
#                   age_yrs = age,
#                   no_days = no_days_i,
#                   bpm = bpm_i,
#                   se_bpm = se_bpm_i
#     )
#     
#     A_cost_calf <- rbind(A_cost_calf, row)
#   }


kable(A_cost_calf)

# Calves 
Es_table_phase1 <- as.data.frame(matrix(ncol = 17, nrow = 0))

colnames(Es_table_phase1) <- c("age_yrs","Lifestage", 
                               "Activity_stages", "no_days", 
                               "mean_bpm", "se_bpm", "mean_bpd",
                               "Vt_mean", "Vt_sd",
                               "Es_perday", "Es_perday_sd",
                               "Es_perday_quant025", "Es_perday_quant975", #2.5% and 97.5% quantile from bootstrap estimates 
                               "Es","Es_sd","Es_quant025","Es_quant975"
)            




Es_table_phase1 <- as_tibble(Es_table_phase1, 
                             col_types = (list(ID = col_integer(), 
                                               age_yrs = col_double(),
                                               Lifestage = col_double(),
                                               Activity_stages = col_character(),
                                               no_days = col_double(),
                                               mean_bpm = col_double(),
                                               mean_bpd = col_double(),
                                               se_bpm = col_double(),
                                               Vt_mean = col_double(),
                                               Vt_sd = col_double(), 
                                               Es_perday = col_double(),
                                               Es_perday_sd  = col_double(),
                                               Es_perday_quant025 = col_double(),
                                               Es_perday_quant975 = col_double(),
                                               Es = col_double(),
                                               Es_sd = col_double(),
                                               Es_quant025 = col_double(),
                                               Es_quant975 = col_double()
                             )
                             )
)



#Original code was run with MC_reps <- 10000  
#and took a very long time
#To test and explore the code, use less reps 

MC_reps = 10000

for (a in seq(from = 1, to = 12, by = 1)){
  
  age_yrs_i <- age_yr_tibble %>% 
    dplyr::filter(age_mth == a)  %>% 
    pull(age_yrs)
  
  age_mid_i <- age_yr_tibble %>% 
    dplyr::filter(age_mth == a-0.5) %>% 
    pull(age_yrs)
  
  #Lifestage <-  "Calf"
  
  strcolname <- as.character(age_yrs_i)
  A_cost_calf_i <- dplyr::filter(A_cost_calf, 
                                 round(A_cost_calf$age_yrs*12) == a)
  
  if (nrow(A_cost_calf_i) == 0) {
    row <- NA
  }else{
    
    Activity_stages <- A_cost_calf_i$Activity_stages
    
    for (act in Activity_stages){
      activity <- act
      Lifestage
      activity
      
      strcolname <- as.character(age_yrs_i)
      
      A_cost_i <- A_cost_reference %>% dplyr::filter(
        Activity_stages == activity & 
          Lifestage == "Calf" 
        & round(age_yrs, 3) == round(age_yrs_i,3))
      
      A_cost_i
      
      # Lifestage <- A_cost_i$Lifestage
      # A_stage <- a
      
      set.seed(12345)
      
      
      #plot(pct_O2)
      #No. of days at each age
      no_days_i <-  A_cost_i$no_days   
      
      #Respiration rates at each activity stage 
      bpm_i <- A_cost_i$bpm 
      bpm_sd_i <- A_cost_i$se_bpm 
      
      #log() computes the natural logarithms (Ln)
      meanlog_bpm_i <- log(bpm_i^2 / sqrt(bpm_sd_i^2 + bpm_i^2))  #location
      meanlog_bpm_sd_i <- sqrt(log(1 + (bpm_sd_i^2 / bpm_i^2)))  #shape
      
      bpm_tibble <- as.data.frame(matrix(ncol = 2, nrow=0))
      colnames(bpm_tibble) <- c("mean_bpm", "sd_bpm")
      bpm_tibble <- as_tibble(bpm_tibble,
                              col_types = (list(ID = col_integer(), 
                                                mean_bpm = col_double(),
                                                sd_bpm = col_double()
                                                
                              )))
      
      
      for (i in seq(from = 1, to = MC_reps, by = 1)){
        
        #sample from lognormal distribution
        bpm <- rlnorm(MC_reps, meanlog_bpm_i, meanlog_bpm_sd_i)  
        # draws <- rlnorm(n=1000000, location, shape)
        # https://msalganik.wordpress.com/2017/01/21/making-sense-of-the-rlnorm-function-in-r/
        # plot(bpm)
        mean_bpm <- mean(bpm)
        sd_bpm <- sd(bpm)
        bpm_row <- tibble(mean_bpm = mean_bpm,
                          sd_bpm = sd_bpm)
        bpm_tibble <- rbind(bpm_tibble, bpm_row) 
        bpm_row <- NA
      }
      
      
      mean_bpm_i <- mean(bpm_tibble$mean_bpm)
      se_bpm_i <- sd(bpm_tibble$mean_bpm)     #sd of mean of means
      
      mean_bpm_reps <- bpm_tibble$mean_bpm
      
      # breath_hold_time <- 1/mean_bpm_reps
      # #plot(breath_hold_time)
      # mean(breath_hold_time)
      # sd(breath_hold_time)
      # 
      # #breaths per day
      # bpd <- 1440/breath_hold_time
      # mean(bpd)
      # sd(bpd)
      # #plot(bpd)
      
      #other option - truncated normal distribution
      #bpm <- rtruncnorm(MC_reps, a=0, b=Inf, mean=bpm_i, sd=bpm_sd_i)
      
      # breaths/day
      bpd <- mean_bpm_reps * 60 * 24
      # plot(bpd)
      bpd_mean_i <-  mean(bpd)
      bpd_sd_i <- sd(bpd)
      
      
      #tidal volume (mass dependent)
      Vt_table_i <- dplyr::filter(
        Vt_table_phase1, 
        round(Vt_table_phase1$age_yrs,digits = 3) == round(age_mid_i,digits =3)
      )
      
      Vt_i <- Vt_table_i$Vt_mean
      Vt_sd_i <- Vt_table_i$Vt_sd
      
      set.seed(12345)
      Vt <- rnorm(MC_reps, Vt_i, Vt_sd_i)
      Vt_mean_i <- mean(Vt)
      Vt_sd_i <- sd(Vt)
      #plot(Vt)
      
      # O2 extraction efficiency
      if (a <= 5) {
        pct_O2_i <- 10.5/100
        pct_O2_sd_i <- 3/100
      } else if (a > 5){
        pct_O2_i <- 11/100
        pct_O2_sd_i <- 2.7/100
      }
      
      pct_O2 <- rnorm(MC_reps, pct_O2_i, pct_O2_sd_i)  
      
      
      #Energetic expenditure per day
      Es_perday <- 0.02 * pct_O2* bpd * Vt   
      #plot(Es_perday)
      
      Es_perday_mean <- mean(Es_perday)
      Es_perday_sd <- sd(Es_perday)
      Es_perday_quant025 <- quantile(Es_perday, 0.025, na.rm = TRUE)
      Es_perday_quant975 <- quantile(Es_perday, 0.975, na.rm = TRUE)
      
      #Energettic expenditure per month
      Es = Es_perday * no_days_i
      #plot(Es)
      Es_mean = mean(Es)
      Es_sd = sd(Es)
      Es_quant025 <- quantile(Es, 0.025, na.rm = TRUE)
      Es_quant975 <- quantile(Es, 0.975, na.rm = TRUE)
      
      
      # "age_yrs", "Es", "Es_sd", "quant025", "quant975" 
      row <- tibble(age_yrs = age_yrs_i,
                    Lifestage = Lifestage,
                    Activity_stages = activity,
                    no_days = no_days_i,
                    mean_bpm = mean_bpm_i,
                    se_bpm = se_bpm_i,
                    mean_bpd = bpd_mean_i,
                    Vt_mean = Vt_mean_i,
                    Vt_sd = Vt_sd_i,
                    Es_perday = Es_perday_mean, 
                    Es_perday_sd = Es_perday_sd, 
                    Es_perday_quant025 = Es_perday_quant025,
                    Es_perday_quant975  = Es_perday_quant975,
                    Es = Es_mean, 
                    Es_sd = Es_sd,
                    Es_quant025 = Es_quant025, 
                    Es_quant975 = Es_quant975)
      
      Es_table_phase1 <- rbind(Es_table_phase1, row)
      row <-  NA
    }
    }
}




kable(Es_table_phase1)

Es_table_phase1 %>% write_csv("data/Es_table_phase1_source_bpm.csv", na = "", append = FALSE)

```

```{r plots_Es_phase1_stacked}

plot_Es_table_phase1 <- Es_table_phase1 %>% 
  ggplot(aes(x = age_yrs, y = Es))+
  geom_errorbar(aes(ymin = Es - Es_sd, ymax = Es + Es_sd),
                colour = "blue", width = 0.02)+
  geom_point()+
  ggtitle("Es table - phase 1")

plot_Es_table_phase1



```

```{r Es_phase1_permth}


Es_table_phase1_permth <- Es_table_phase1

Es_table_phase1_permth$age_mth <- round(Es_table_phase1_permth$age_yrs *12)

# Es_table_phase1_permth$Es_perday <- Es_table_phase1_permth$Es / Es_table_phase1_permth$no_days
# Es_table_phase1_permth$Es_sd_perday <- Es_table_phase1_permth$Es_sd / Es_table_phase1_permth$no_days


#pull out blank Es_subtable
Es_subtable <- Es_table_phase1 %>% dplyr::filter(age_yrs >999, Lifestage == Lifestage)
kable(Es_subtable)


Es_table_phase1_permth  <- Es_subtable %>%  dplyr::select(age_yrs, Lifestage, no_days, Es, Es_sd, Es_perday, Es_perday_sd)
Es_table_phase1_permth$age_mth <- round(Es_table_phase1_permth$age_yrs *12)

## Calculate sum of Es for phase 1 (per mth)
for (i in seq(from = 1, to = 12, by = 1)){
  
    age <- age_yr_tibble %>% dplyr::filter(age_mth == i) %>%  pull(age_yrs)
    age_mth <-  i
  
  Es_subtable <- Es_table_phase1 %>% dplyr::filter(age_yrs == age)
  no_days <- sum(Es_subtable$no_days)
  Es <- sum(Es_subtable$Es)
  
  sum_of_variances <- 0
  for (row in 1:nrow(Es_subtable)){
    #for (i in c( 0.33, 0.42, 0.5)){ 
    Es_subtable_i <- Es_subtable[row, "Es"]
    Es_sd_i <- Es_subtable[row, "Es_sd"]
    sum_of_variances <- sum_of_variances + (Es_sd_i)^2
  }
  Es_sd  <-  sqrt(sum_of_variances$Es_sd)
  
  
  
  newRow <- tibble(age_yrs = age,
                   age_mth = i,
                   Lifestage = Lifestage,
                   no_days = no_days ,
                   Es = Es, 
                   Es_sd = Es_sd
  )
  
  Es_table_phase1_permth <- rbind(Es_table_phase1_permth, newRow)
}






Es_table_phase1_permth$Es_perday <- Es_table_phase1_permth$Es / Es_table_phase1_permth$no_days
Es_table_phase1_permth$Es_sd_perday <- Es_table_phase1_permth$Es_sd / Es_table_phase1_permth$no_days


Es_table_phase1_permth %>% write_csv("data/Es_table_phase1_permth_source_bpm.csv", na = "", append = FALSE)

```

```{r plots_Es_phase1_permth}


plot_Es_table_phase1_permth <- Es_table_phase1_permth %>% 
  #dplyr::filter(age_yrs == i) %>% 
  ggplot(aes(x = age_mth-0.5, y =Es)) +
  geom_errorbar(aes(ymin = Es - Es_sd, ymax = Es + Es_sd),
                linetype = 3, colour = 'gray40', width = 0) +
  geom_point() +
  xlab("Age (months)") +
  ylab(bquote('Energetic expenditure (MJ day'^'-1'*')')) +

  
  scale_x_continuous(breaks = scales::pretty_breaks(n = 11))+ 
  #limits = c(0, 30)) +  # max x-axis 30 yrs. 
  scale_y_continuous(label = comma, 
                     breaks = scales::pretty_breaks(n = 10)
                     #limits = c(0,1500)
                     ) +
  theme_bw()+
  theme(panel.grid = element_blank())+
  theme(axis.title.x = element_text(size = rel(1.4),
                                    colour = "black"))+
  theme(axis.title.y = element_text(size = rel(1.4),
                                    colour = "black"))+
  theme(axis.text = element_text(size = rel(1.2),
                                 colour = "black"))  
#ggtitle("Es table Phase 1 - per mth")

plot_Es_table_phase1_permth


plot_Es_table_phase1_permth_black <- Es_table_phase1_permth %>% 
  #dplyr::filter(age_yrs == i) %>% 
  ggplot(aes(x = age_mth-0.5, y =Es)) +
  geom_errorbar(aes(ymin = Es - Es_sd, ymax = Es + Es_sd),
                linetype = 3, colour = 'white', width = 0, size = 1) +
  geom_point(colour = "white", size = 3) +
  xlab("Age (months)") +
  ylab(bquote('Energetic expenditure (MJ day'^'-1'*')')) +
  
  scale_x_continuous(breaks = scales::pretty_breaks(n = 11))+ 
  #limits = c(0, 30)) +  # max x-axis 30 yrs. 
  scale_y_continuous(label = comma, 
                     breaks = scales::pretty_breaks(n = 10)
                     #limits = c(0,500)
                     )+
  #scale_y_continuous(label = function(x){(x/1000)}, breaks = scales::pretty_breaks(n = 8), 
  
  theme_bw()+
  theme(panel.grid = element_blank())+
  theme(legend.position = "none")+
  theme(legend.background = element_rect(fill = "black"))+
  theme(legend.text = element_text(colour = "white", size = rel(1)))+
  theme(legend.key = element_rect(fill = "transparent"))+ #colour = "transparent"))+
  ggtitle(element_blank()) +
  theme(plot.background = element_rect(fill = "black"))+
  theme(panel.background = element_rect(fill = "black"))+
  theme(panel.border = element_blank())+
  theme(axis.line = element_line(size = 1, colour = "white"))+
  theme(axis.text = element_text(colour = "white", size = rel(1.2)))+
  theme(axis.title.y = element_text(colour = "white", size = rel(1.2), angle = 90))+
  theme(axis.title.x = element_text(colour = "white", size = rel(1.4)))+
  theme(axis.ticks = element_line(colour="white"))


plot_Es_table_phase1_permth_black

```

```{r plots_Es_phase1_mthly_perday}
plot_Es_table_phase1_mthly_perday <- Es_table_phase1_permth %>% 
  #dplyr::filter(age_yrs == i) %>% 
  ggplot(aes(x = age_mth-0.5, y =Es_perday)) +
  geom_errorbar(aes(ymin = Es_perday - Es_perday_sd, ymax = Es_perday + Es_perday_sd),
                linetype = 3, colour = 'gray40', width = 0) +
  geom_point(aes(x = age_mth-0.5, y =Es_perday)) +
  xlab("Age (months)") +
  ylab(bquote('Energetic expenditure (MJ day'^'-1'*')')) +
  #ylab(bquote('GER (MJ day '^'-1'*')'))
  
  scale_x_continuous(breaks = scales::pretty_breaks(n = 11))+ 
  #limits = c(0, 30)) +  # max x-axis 30 yrs. 
  scale_y_continuous(label = comma, 
                     breaks = scales::pretty_breaks(n = 10),
                     limits = c(0,500))+
  theme_bw()+
  theme(panel.grid = element_blank())+
  theme(axis.title.x = element_text(size = rel(1.4),
                                    colour = "black"))+
  theme(axis.title.y = element_text(size = rel(1.4),
                                    colour = "black"))+
  theme(axis.text = element_text(size = rel(1.2),
                                 colour = "black"))  
#ggtitle("Es table Phase 1 - per mth")

plot_Es_table_phase1_mthly_perday


plot_Es_table_phase1_mthly_perday_black <- Es_table_phase1_permth %>% 
  #dplyr::filter(age_yrs == i) %>% 
  ggplot(aes(x = age_mth-0.5, y =Es_perday)) +
  geom_errorbar(aes(ymin = Es_perday - Es_perday_sd, ymax = Es_perday + Es_perday_sd),
                linetype = 3, colour = 'white', width = 0) +
  geom_point(colour = "white", size = 2) +
  
  xlab("Age (months)") +
  ylab(bquote('Energetic expenditure (MJ day'^'-1'*')')) +
  #ylab(bquote('GER (MJ day '^'-1'*')'))
  
  scale_x_continuous(breaks = scales::pretty_breaks(n = 11))+ 
  #limits = c(0, 30)) +  # max x-axis 30 yrs. 
  scale_y_continuous(label = comma, 
                     breaks = scales::pretty_breaks(n = 10),
                     limits = c(0,500))+
  theme_bw()+
  theme(panel.grid = element_blank())+

  #theme(panel.grid = element_blank())+
  theme(legend.position = "none")+
  theme(legend.background = element_rect(fill = "black"))+
  theme(legend.text = element_text(colour = "white", size = rel(1)))+
  theme(legend.key = element_rect(fill = "transparent"))+ #colour = "transparent"))+
  ggtitle(element_blank()) +
  theme(plot.background = element_rect(fill = "black"))+
  theme(panel.background = element_rect(fill = "black"))+
  theme(panel.border = element_blank())+
  theme(axis.line = element_line(size = 1, colour = "white"))+
  theme(axis.text = element_text(colour = "white", size = rel(1.2)))+
  theme(axis.title.y = element_text(colour = "white", size = rel(1.4), angle = 90))+
  theme(axis.title.x = element_text(colour = "white", size = rel(1.4)))+
  theme(axis.ticks = element_line(colour="white"))



plot_Es_table_phase1_mthly_perday_black


```
