---
title:  "Energy Expenditure (Es) Sensitivity Analysis - Lactating"
author: "Selina Agbayani"
date: "10 March 2022 - code updated `r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
  github_document:
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(error = TRUE)
knitr::opts_chunk$set(warning = TRUE)


## Setup

# Initialize all libraries, set paths for output figures, then import the gw_observations.csv
# install.packages("tidyr")
# install.packages("tidyverse")
# install.packages("dplyr")
# install.packages("ggplot2")
# install.packages("knitr")
# install.packages("nls2")
# install.packages("nlstools")
# install.packages("nlme")
# install.packages("minpack.lm")
# install.packages("scales")
# install.packages("ggpmisc")
# install.packages("extrafont")
#install.packages("truncnorm")



library(tidyverse)
# library(tidyr)
# library(dplyr)
# library(ggplot2)
library(knitr)
library(nls2)
library(nlstools)
library(nlme)
library(minpack.lm)
library(scales)
library(ggpmisc)
library(reshape2)
library(extrafont)
library(truncnorm)

# #quiet col types messages
# options(readr.show_col_types = FALSE)

```


```{r functions, include=FALSE}
#Call R script with custom functions
source("../functions.R", local = knitr::knit_global())
```   


```{r setpaths}
# Set path for output figures: 
Figurespath <- paste0(getwd(), "/Es/figures", collapse = NULL)
Figurespath
# Set path for input & output data  
datapath <- paste0(getwd(), "/data", collapse = NULL) 
datapath




```

```{r read_in_data}
# Read in Tidal Volume table - Vt

Es_sensAnalysis_phase1 <- as_tibble(
  read_csv("data/Es_sensAnalysis_phase1_source_bpm.csv"),
  col_types = (list(cols(age_yrs = col_double(),
                         Lifestage = col_character(),
                         Activity_stages = col_character(),
                         no_days = col_double(),
                         MC_variable = col_character(),
                         mean_bpm = col_double(),
                         se_bpm = col_double(),
                         mean_bpd = col_double(),
                         Vt_mean = col_double(),
                         Vt_sd = col_double(),
                         Es_perday = col_double(),
                         Es_perday_sd = col_double(),
                         Es_perday_quant025 = col_double(),
                         Es_perday_quant975 = col_double(),
                         Es = col_double(),
                         Es_sd = col_double(),
                         Es_quant025 = col_double(),
                         Es_quant975 = col_double()
  )
  )
  )
)

Es_sensAnalysis_phase2_peryear <- as_tibble(
  read_csv("data/Es_sensAnalysis_phase2_peryear_source_bpm.csv"), 
  col_types = (list(cols(
    age_yrs = col_double(),
    Lifestage = col_character(),
    no_days = col_double(),
    Es = col_double(),
    Es_sd = col_double(),
    Es_perday = col_double(),
    Es_sd_perday = col_double()
  )
  )
  )
)


Vt_table_phase1 <- as_tibble(
  read_csv("data/Vt_table_phase1.csv"),                                
  col_types = (list(cols(age_yrs = col_double(),
                         Vt_mean = col_double(),
                         Vt_sd = col_double(),
                         quant025 = col_double(),
                         quant975 = col_double()
  )
  )
  )
)


Vt_table_phase2 <- as_tibble(
  read_csv("data/Vt_table_phase2.csv"),                                
  col_types = (list(cols(age_yrs = col_double(),
                         Vt_mean = col_double(),
                         Vt_sd = col_double(),
                         quant025 = col_double(),
                         quant975 = col_double()
  )
  )
  )
)




Vt_table_phase2_f <- as_tibble(
  read_csv("data/Vt_table_phase2_f.csv"),                                
  col_types = (list(cols(age_yrs = col_double(),
                         Vt_mean_f = col_double(),
                         Vt_sd_f = col_double(),
                         quant025_f = col_double(),
                         quant975_f = col_double()
  )
  )
  )
)



# Read in Activity Cost Reference data from csv  ORIGINAL SOURCE VALUES
A_cost_reference <- as_tibble(
  read_csv("data/ActivityCost_ReferenceData_BreathsPerDay_Table_VA_2017_original_sources.csv"),
  col_types = (list(cols(ID = col_double(),
                         Lifestage = col_character(),
                         Description = col_character(),
                         Activity_stages = col_character(),
                         no_days = col_double(),
                         source_no_days = col_character(),
                         bpm = col_double(),
                         se_bpm = col_double(),
                         source_bpm = col_character(),
                         age_yrs = col_double(),
                         age_yrs_min = col_double(),
                         age_yrs_max = col_double(),
                         pct_O2 = col_double(),
                         pct_O2_sd = col_double()
  )
  )
  )
)

kable(head(A_cost_reference))

Activity_days <- A_cost_reference %>% dplyr::select(Lifestage, Activity_stages, no_days) %>%  
  group_by(Lifestage, Activity_stages) %>% 
  summarise(no_days = sum(no_days))

kable(head(Activity_days))



age_yr_tibble <- as_tibble(
  read_csv("data/age_yr_tibble.csv"), 
  col_types = (list(ID = col_integer(),
                    month = col_character(),
                    no_days_in_mth = col_double(),
                    age_mth = col_double(),
                    no_days_cumul = col_double(),
                    age_yrs = col_double()
  )
  )
)



```

Total metabolic energy expenditure at a given stage (E~s~) 
------------------------------------------------------------------------

E~s~ = 0.02 x %O~2~ x T~s~ x R~s~ x V~t~ - Sumich (1986)

where:  

0.02 - Amount of heat produced in MJ/L O2 consumed (Kleiber 1961)  
%O~2~ - Extraction efficiency per breath  
T~s~ - The no. of days in that stage  
R~s~ - Respiration rate (breaths/day)  
V~t~ - Tidal lung volume (L)  

```{r Es_lact}
#Original code was run with MC_reps <- 10000  and took a very long time
#To test and explore the code, use less reps 

MC_reps = 100

# lactating only 
Lifestage <-  "Lactating"
activity_stages <- Activity_days %>%
  filter(Lifestage == "Lactating")

activity_stages  <-  activity_stages$Activity_stages

Es_sensAnalysis_lact_females <- as.data.frame(matrix(ncol = 18, nrow = 0))

cnames <- c("age_yrs","Lifestage","Activity_stages","MC_variable",
            "no_days", "mean_bpm", "se_bpm", "mean_bpd",
            "Vt_mean", "Vt_sd",
            "Es_perday", "Es_perday_sd",
            "Es_perday_quant025", "Es_perday_quant975", #2.5% and 97.5% quantile from bootstrap estimates
            "Es","Es_sd","Es_quant025","Es_quant975"
)
     

colnames(Es_sensAnalysis_lact_females) <- cnames

Es_sensAnalysis_lact_females <- 
  as_tibble(Es_sensAnalysis_lact_females,
            col_types = (list(ID = col_integer(), 
                              age_yrs = col_double(),
                              Lifestage = col_double(),
                              Activity_stages = col_double(),
                              MC_variable = col_character(),
                              no_days = col_double(),
                              mean_bpm = col_double(),
                              se_bpm = col_double(),  
                              mean_bpd = col_double(),
                              Vt_mean = col_double(),
                              Vt_sd = col_double(),
                              Es_perday = col_double(),
                              Es_perday_sd  = col_double(),
                              Es_perday_quant025  = col_double(),
                              Es_perday_quant975 = col_double(),
                              Es = col_double(),
                              Es_sd = col_double(),
                              Es_quant025 = col_double(),
                              Es_quant975 = col_double()
            )
            )
  )




for (age in seq(from = 8, to = 75, by = 1)){
  
  for (MC_var in c("all","Rs", "Vt", "pctO2")){
    
    
    for (activity in activity_stages){   
      
      strcolname <- as.character(age)
      
      A_cost_i <- filter(A_cost_reference, 
                         Lifestage == Lifestage &
                           Activity_stages == activity &
                           age >= age_yrs_min &
                           age <= age_yrs_max)
      
      if (nrow(A_cost_i) > 0) {
        Vt_table_i <- filter(Vt_table_phase2, age_yrs == age-0.5)

        
        # O2 extraction efficiency
        pct_O2_i <- A_cost_i$pct_O2 /100
        if (MC_var == "all" || MC_var == "pctO2"){
          pct_O2_sd_i <- A_cost_i$pct_O2_sd /100
        } else {
          pct_O2_sd_i <- 0
        }
        
        set.seed(12345)
        pct_O2 <- rnorm(MC_reps, pct_O2_i, pct_O2_sd_i)  
        
        #No. of days at each actvity stage
        no_days_i <-  sum(A_cost_i$no_days)   
        
        #Respiration rates at each activity stage 
        bpm_i <- A_cost_i$bpm 
        bpm_sd_i <- A_cost_i$se_bpm 
        
        meanlog_bpm_i <- log(bpm_i^2 / sqrt(bpm_sd_i^2 + bpm_i^2))
        meanlog_bpm_sd_i <- sqrt(log(1 + (bpm_sd_i^2 / bpm_i^2)))
        
        bpm_tibble <- as.data.frame(matrix(ncol = 2, nrow=0))
        colnames(bpm_tibble) <- c("mean_bpm", "sd_bpm")
        bpm_tibble <- 
          as_tibble(bpm_tibble,
                    col_types = (list(ID = col_integer(), 
                                      mean_bpm = col_double(),
                                      sd_bpm = col_double()
                                      
                    )))
        
        for (i in seq(from = 1, to = MC_reps, by = 1)){
          
          #sample from lognormal distribution
          bpm <- rlnorm(MC_reps, meanlog_bpm_i, meanlog_bpm_sd_i)  
          # draws <- rlnorm(n=1000000, location, shape)
          # https://msalganik.wordpress.com/2017/01/21/making-sense-of-the-rlnorm-function-in-r/
          # plot(bpm)
          mean_bpm <- mean(bpm)
          sd_bpm <- sd(bpm)
          bpm_row <- tibble(mean_bpm = mean_bpm,
                            sd_bpm = sd_bpm)
          bpm_tibble <- rbind(bpm_tibble, bpm_row) 
          bpm_row <- NA
        }
        
        
        mean_bpm_i <- mean(bpm_tibble$mean_bpm)
        se_bpm_i <- sd(bpm_tibble$mean_bpm)     #sd of mean of means
        
        mean_bpm_reps <- bpm_tibble$mean_bpm
        
       
        # breaths/day
        bpd <- mean_bpm_reps * 60 * 24
        # plot(bpd)
        bpd_mean_i <-  mean(bpd)
        
        if (MC_var == "all" || MC_var == "Rs"){
          bpd_sd_i <- sd(bpd)  
        } else {
          bpd_sd_i = 0
        }
        
        #tidal volume (mass dependent)
        Vt_i <- Vt_table_i$Vt_mean
        
        if (MC_var == "all" || MC_var == "Vt"){
          Vt_sd_i <- Vt_table_i$Vt_sd  
        } else {
          Vt_sd_i = 0
        }
        
        
        set.seed(12345)
        Vt <- rnorm(MC_reps, Vt_i, Vt_sd_i)
        #plot(Vt)
        Vt_mean_i <- mean(Vt)
        Vt_sd_i <- sd(Vt)
        #plot(Vt)
        
        Es_perday <- 0.02 * pct_O2* bpd * Vt  # * Ts_i 
        #plot(MR_perday)
        
        Es_perday_mean <- mean(Es_perday)
        Es_perday_sd <- sd(Es_perday)
        Es_perday_quant025 <- quantile(Es_perday, 0.025, na.rm = TRUE)
        Es_perday_quant975 <- quantile(Es_perday, 0.975, na.rm = TRUE)
        
        Es = Es_perday * no_days_i
        #plot(Es)
        Es_mean = mean(Es)
        Es_sd = sd(Es)
        Es_quant025 <- quantile(Es, 0.025, na.rm = TRUE)
        Es_quant975 <- quantile(Es, 0.975, na.rm = TRUE)
        
        
        # "age_yrs", "Es", "Es_sd", "quant025", "quant975" 
        row <- tibble(age_yrs = age,
                      Lifestage = Lifestage,
                      Activity_stages = activity,
                      no_days = no_days_i,
                      MC_variable = MC_var,
                      mean_bpm = mean_bpm_i,
                      se_bpm = se_bpm_i,
                      Es_perday = Es_perday_mean, 
                      Es_perday_sd = Es_perday_sd, 
                      Es_perday_quant025 = Es_perday_quant025,
                      Es_perday_quant975  = Es_perday_quant975,
                      Es = Es_mean, 
                      Es_sd = Es_sd,
                      Es_quant025 = Es_quant025, 
                      Es_quant975 = Es_quant975)
        
        Es_sensAnalysis_lact_females <- rbind(Es_sensAnalysis_lact_females, row)
      }
    }    
  }}



kable(head(Es_sensAnalysis_lact_females))



Es_sensAnalysis_lact_females %>% write_csv("data/Es_sensAnalysis_lact_females_source_bpm.csv", na = "", append = FALSE)

```

```{r Es_lact_stacked}
Es_sensAnalysis_lact_females <- read_csv("data/Es_sensAnalysis_lact_females_source_bpm.csv")

plot_Es_sensAnalysis_lact_females <- Es_sensAnalysis_lact_females %>% 
  filter(age_yrs<=40) %>% 
  ggplot(aes(x = age_yrs, y = Es_perday))+
  geom_errorbar(aes(ymin = Es_perday - Es_perday_sd, ymax = Es_perday + Es_perday_sd),
                linetype = 1, colour = "gray40", width = 0.02)+
   geom_point(size = 0.5)+
  #  geom_ribbon(aes(ymin = Es_perday - Es_perday_sd, ymax = Es_perday + Es_perday_sd),
  #               fill = "gray70")+
  # geom_line(linewidth = 0.5)+
   facet_grid(MC_variable ~ Activity_stages,
              labeller = label_wrap_gen(width = 2, 
                                        multi_line = TRUE)) +
   xlab("Age (years)") +
   ylab(bquote('Energetic expenditure (MJ day '^'-1'*')')) + 
   scale_x_continuous(breaks = scales::pretty_breaks(n = 5),
                     limits = c(0, 30.5))+
   #limits = c(0, 30.5), expand=c(0,0)) +  # max x-axis 30 yrs.
   scale_y_continuous(label=comma,
                      breaks = scales::pretty_breaks(n = 5),
                      limits =  c(0, 2500))+

 
  #ggtitle("Lactating")+
  theme_bw() +
  theme(panel.grid = element_blank())+
  theme(legend.position.inside = 0)+
  # theme(plot.background = element_rect(fill = "black"))+
  # theme(panel.background = element_rect(fill = "black"))+
  #theme(panel.border = element_blank())+
  theme(axis.line = element_line(linewidth = 1, colour = "gray75"))+
  theme(axis.text = element_text(colour = "black", size = rel(1)))+
  theme(axis.title.y = element_text(colour = "black", 
                                    size = rel(1), angle = 90))+
  theme(axis.title.x = element_text(colour = "black", 
                                    size = rel(1)))+
    theme(strip.background = element_rect(colour = "transparent", fill = "transparent"))+
  theme(strip.text = element_text(colour = "black", size = rel(1)))

plot_Es_sensAnalysis_lact_females


```

```{r Es_lact_peryear}

# lactating only
Es_subtable_lact <- Es_sensAnalysis_lact_females %>% dplyr::filter(age_yrs >999, Lifestage == Lifestage)
kable(head(Es_sensAnalysis_lact_females))

Es_lact_table  <- Es_subtable_lact %>%  
  select(age_yrs, Lifestage, no_days, MC_variable, Es, Es_sd)



## Calculate sum of Es for pregnant females aged 8+
for (age in seq(from = 8, to = 75, by = 1)){
  for (MC_var in c("all","Rs", "Vt", "pctO2")){
    max_age <- age + 1
    Es_subtable_lact <- 
      Es_sensAnalysis_lact_females %>%
      dplyr::filter(age_yrs==age & MC_variable == MC_var) %>% 
      dplyr::select(age_yrs, Lifestage, Activity_stages, no_days, MC_variable, Es, Es_sd)
    
    no_days <- sum(Es_subtable_lact$no_days)
    Es_lact <- sum(Es_subtable_lact$Es)
    
    sum_of_variances <- 0
    for (row in 1:nrow(Es_subtable_lact)){
      Es_subtable_lact_i <- Es_subtable_lact[row, "Es"]
      Es_sd_i <- Es_subtable_lact[row, "Es_sd"]
      sum_of_variances <- sum_of_variances + (Es_sd_i)^2
    }
    Es_lact_sd  <-  sqrt(sum_of_variances$Es_sd)
    
    
    
    newRow <- tibble(age_yrs = age,
                     Lifestage = Lifestage,
                     no_days = no_days,
                     MC_variable = MC_var, 
                     Es = Es_lact,
                     Es_sd = Es_lact_sd
    )
    
    Es_lact_table <- rbind(Es_lact_table, newRow)
  }}


Es_lact_table$Es_perday <- Es_lact_table$Es / Es_lact_table$no_days 
Es_lact_table$Es_sd_perday <- Es_lact_table$Es_sd / Es_lact_table$no_days

Es_lact_table %>% 
  write_csv("data/Es_sensAnalysis_lact_peryear_source_bpm.csv", 
            na = "", append = FALSE)

```


```{r plots_Es_lact_peryear}

plot_Es_lact_table <- Es_lact_table %>% 
  filter(age_yrs <= 30) %>% 
  ggplot(aes(x = age_yrs, y =Es_perday)) +
  # geom_errorbar(aes(ymin = Es_perday - Es_sd_perday,
  #                   ymax = Es_perday + Es_sd_perday),
  #               linetype = 1, colour = 'gray40', width = 0) +
  # geom_point(size = 0.5) +
  geom_ribbon(aes(ymin = Es_perday - Es_sd_perday, ymax = Es_perday + Es_sd_perday),
                fill = "gray70")+
  geom_line(linewidth = 0.5)+
  facet_grid(~MC_variable)+
  xlab("Age (years)") +
  ylab(bquote('Energetic expenditure (MJ day '^'-1'*')')) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10),
                     limits = c(0, 30.5))+
  #limits = c(0, 30.5), expand=c(0,0)) +  # max x-axis 30 yrs.
  scale_y_continuous(label=comma,
                     breaks = scales::pretty_breaks(n = 10),
                     limits =  c(0, 1500))+
  
  #limits = c(0,1400), expand=c(0,0))+
  ggtitle("Lactating")+
  theme_bw() +
  theme(panel.grid = element_blank())+
  theme(legend.position.inside= 0)+
  # theme(plot.background = element_rect(fill = "black"))+
  # theme(panel.background = element_rect(fill = "black"))+
  #theme(panel.border = element_blank())+
  theme(axis.line = element_line(linewidth = 1, colour = "gray75"))+
  theme(axis.text = element_text(colour = "black", size = rel(1)))+
  theme(axis.title.y = element_text(colour = "black", 
                                    size = rel(1), angle = 90))+
  theme(axis.title.x = element_text(colour = "black", 
                                    size = rel(1)))+
  theme(strip.background = element_rect(colour = "transparent", fill = "transparent"))+
  theme(strip.text = element_text(colour = "black", size = rel(1)))

plot_Es_lact_table



```

