---
title: "Es - Sensitivity Analysis - source - Phase 2"
author: "S. Agbayani"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  github_document:
  html_document:
  pdf_document:
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(error = TRUE)

## Setup

# Initialize all libraries, set paths for output figures, then import the gw_observations.csv
# install.packages("tidyr")
# install.packages("tidyverse")
# install.packages("dplyr")
# install.packages("ggplot2")
# install.packages("knitr")
# install.packages("nls2")
# install.packages("nlstools")
# install.packages("nlme")
# install.packages("minpack.lm")
# install.packages("scales")
# install.packages("ggpmisc")
# install.packages("extrafont")
#install.packages("truncnorm")



library(tidyverse)
# library(tidyr)
# library(dplyr)
# library(ggplot2)
library(knitr)
library(nls2)
library(nlstools)
library(nlme)
library(minpack.lm)
library(scales)
library(ggpmisc)
library(reshape2)
library(extrafont)
library(truncnorm)

source("functions.R")

```

```{r setpaths}
# Set path for output figures: 
Figurespath <- paste0(getwd(), "/FMR/figures", collapse = NULL)
Figurespath
# Set path for input & output data  
datapath <- paste0(getwd(), "/data", collapse = NULL) 
datapath




```

```{r read_in_data}
# Read in Tidal Volume table - Vt

Es_sensAnalysis_phase1 <-
  as_tibble(read_csv("data/Es_sensAnalysis_phase1_source_bpm.csv"),
            col_types = (list(cols(age_yrs = col_double(),
                         Lifestage = col_character(),
                         Activity_stages = col_character(),
                         no_days = col_double(),
                         MC_variable = col_character(),
                         mean_bpm = col_double(),
                         se_bpm = col_double(),
                         mean_bpd = col_double(),
                         Vt_mean = col_double(),
                         Vt_sd = col_double(),
                         Es_perday = col_double(),
                         Es_perday_sd = col_double(),
                         Es_perday_quant025 = col_double(),
                         Es_perday_quant975 = col_double(),
                         Es = col_double(),
                         Es_sd = col_double(),
                         Es_quant025 = col_double(),
                         Es_quant975 = col_double()
            )
            )
            )
  )

Vt_table_phase1 <- 
  as_tibble(read_csv("data/Vt_table_phase1.csv"), 
            col_types = (list(cols(age_yrs = col_double(),
                                   Vt_mean = col_double(),
                                   Vt_sd = col_double(),
                                   quant025 = col_double(),
                                   quant975 = col_double()
            )
            )
            )
  )

                             
Vt_table_phase2 <- 
  as_tibble(read_csv("data/Vt_table_phase2.csv"),
            col_types = (list(cols(age_yrs = col_double(),
                                   Vt_mean = col_double(),
                                   Vt_sd = col_double(),
                                   quant025 = col_double(),
                                   quant975 = col_double()
            )
            )
            )
  )




Vt_table_phase2_f <- 
  as_tibble(read_csv("data/Vt_table_phase2_f.csv"), 
            col_types = (list(cols(age_yrs = col_double(),
                                   Vt_mean_f = col_double(),
                                   Vt_sd_f = col_double(),
                                   quant025_f = col_double(),
                                   quant975_f = col_double()
            )
            )
            )
  )



# Read in Activity Cost Reference data from csv  ORIGINAL SOURCE VALUES
A_cost_reference <- as_tibble(
  read_csv("data/ActivityCost_ReferenceData_BreathsPerDay_Table_VA_2017_original_sources.csv"),
  col_types = (list(cols(ID = col_double(),
                         Lifestage = col_character(),
                         Description = col_character(),
                         Activity_stages = col_character(),
                         no_days = col_double(),
                         source_no_days = col_character(),
                         bpm = col_double(),
                         se_bpm = col_double(),
                         source_bpm = col_character(),
                         age_yrs = col_double(),
                         age_yrs_min = col_double(),
                         age_yrs_max = col_double(),
                         pct_O2 = col_double(),
                         pct_O2_sd = col_double()
  )
  )
  )
)

kable(A_cost_reference)

Activity_days <- A_cost_reference %>% 
  select(Lifestage, Activity_stages, no_days) %>%  
  group_by(Lifestage, Activity_stages) %>% 
  summarise(no_days = sum(no_days))

kable(Activity_days)



age_yr_tibble <- as_tibble(
  read_csv("data/age_yr_tibble.csv"), 
  col_types = (list(ID = col_integer(),
                    month = col_character(),
                    no_days_in_mth = col_double(),
                    age_mth = col_double(),
                    no_days_cumul = col_double(),
                    age_yrs = col_double()
  )
  )
)



```

Es - Total metabolic energy expenditure at a given stage 0.02 - Amount of heat produced in MJ/L O2 consumed (Kleiber 1961)  
%O2 - Extraction efficiency per breath Ts - The no. of days in that stage Rs - Respiration rate (breaths/day) Vt - Tidal lung volume (L)

Es = 0.02 x %O2 x Ts x Rs x Vt - Sumich (1986)

```{r Es_phase2}
MC_reps = 10000

Lifestage <-  "Juvenile/Adult"
Lifestage
activity_stages <- Activity_days %>%
  dplyr::filter(Lifestage == "Juvenile/Adult")
activity_stages  <-  activity_stages$Activity_stages
activity_stages

A_cost_reference_phase2 <- A_cost_reference %>% dplyr::filter(Lifestage == "Juvenile/Adult")
A_cost_reference_phase2

A_cost_phase2 <-  A_cost_reference_phase2 %>% 
  filter(age_yrs == 0) %>% 
  select(Lifestage, no_days, bpm, se_bpm) 
#pulling blank tibble

#A_cost_tibble <- A_cost_reference_phase2 
# Lifestage <- "Juvenile/Adult"
no_days <- sum(A_cost_reference_phase2$no_days)
Lifestage
no_days
bpm <- (sum(A_cost_reference_phase2$no_days * A_cost_reference_phase2$bpm))/no_days
se_bpm <- sqrt(sum(A_cost_reference_phase2$se_bpm^2))

row <- tibble(Lifestage = Lifestage,
              no_days = no_days,
              bpm = bpm,
              se_bpm = se_bpm
)


A_cost_phase2 <- rbind(A_cost_phase2, row)

kable(A_cost_phase2)

#adult/juveniles
Es_sensAnalysis_phase2 <- as.data.frame(matrix(ncol = 18, nrow = 0))

cnames <- c("age_yrs","Lifestage","Activity_stages","MC_variable",
            "no_days", "mean_bpm", "se_bpm", "mean_bpd",
            "Vt_mean", "Vt_sd",
            "Es_perday", "Es_perday_sd",
            "Es_perday_quant025", "Es_perday_quant975", #2.5% and 97.5% quantile from bootstrap estimates
            "Es","Es_sd","Es_quant025","Es_quant975"
)

colnames(Es_sensAnalysis_phase2) <- cnames

Es_sensAnalysis_phase2 <- 
  as_tibble(Es_sensAnalysis_phase2,
            col_types = (list(ID = col_integer(), 
                              age_yrs = col_double(),
                              Lifestage = col_double(),
                              Activity_stages = col_double(),
                              MC_variable = col_character(),
                              no_days = col_double(),
                              mean_bpm = col_double(),
                              se_bpm = col_double(),  
                              mean_bpd = col_double(),
                              Vt_mean = col_double(),
                              Vt_sd = col_double(),
                              Es_perday = col_double(),
                              Es_perday_sd  = col_double(),
                              Es_perday_quant025  = col_double(),
                              Es_perday_quant975 = col_double(),
                              Es = col_double(),
                              Es_sd = col_double(),
                              Es_quant025 = col_double(),
                              Es_quant975 = col_double()
            )
            )
  )

#Es_table_phase2 <- Es_table_phase1



for (age in seq(from = 1, to = 31, by = 1)){
  
  for (MC_var in c("all","Rs", "Vt", "pctO2")){
    
    if (age == 1) {
      age_tibble <- age_yr_tibble %>% dplyr::filter(age_mth == 6)  
      Vt_age <- age_tibble$age_yrs   #calculate age_yrs (do not round up)
      
    }else{
      Vt_age <- age -0.5
    }
    
    
    
    # for (a in c("calving grounds", "northbound", "foraging", "southbound")){
    for (activity in activity_stages){
      
      Lifestage
      activity
      
      strcolname <- as.character(age)
      
      A_cost_i <- A_cost_reference %>% dplyr::filter(
        Activity_stages == activity & 
          Lifestage == "Juvenile/Adult" 
        & age_yrs_min <= age
        & age_yrs_max >= age)
      
      A_cost_i
      
      if (nrow(A_cost_i) > 0) {
        
        if (age == 1){
          Vt_table_i <- 
            dplyr::filter(Vt_table_phase1, 
                          round(age_yrs, 3) == round(Vt_age,3))
          
        } else { 
          Vt_table_i <- 
            dplyr::filter(Vt_table_phase2, 
                          round(age_yrs, 3) == round(Vt_age,3))
        }
        
        
        
        # O2 extraction efficiency
        pct_O2_i <- A_cost_i$pct_O2 /100
        if (MC_var == "all" || MC_var == "pctO2"){
          pct_O2_sd_i <- A_cost_i$pct_O2_sd /100
        } else {
          pct_O2_sd_i <- 0
        }
        
        set.seed(12345)
        pct_O2 <- rnorm(MC_reps, pct_O2_i, pct_O2_sd_i)  
        #plot(pct_O2)
        #No. of days at each activity stage
        no_days_i <-  sum(A_cost_i$no_days)   
        
        #Respiration rates at each activity stage 
        bpm_i <- A_cost_i$bpm 
        bpm_sd_i <- A_cost_i$se_bpm  
        
        meanlog_bpm_i <- log(bpm_i^2 / sqrt(bpm_sd_i^2 + bpm_i^2))
        meanlog_bpm_sd_i <- sqrt(log(1 + (bpm_sd_i^2 / bpm_i^2)))
        
        bpm_tibble <- as.data.frame(matrix(ncol = 2, nrow=0))
        colnames(bpm_tibble) <- c("mean_bpm", "sd_bpm")
        bpm_tibble <- as_tibble(bpm_tibble,
                                col_types = (list(ID = col_integer(), 
                                                  mean_bpm = col_double(),
                                                  sd_bpm = col_double()
                                                  
                                )))
        
        for (i in seq(from = 1, to = MC_reps, by = 1)){
          
          #sample from lognormal distribution
          bpm <- rlnorm(MC_reps, meanlog_bpm_i, meanlog_bpm_sd_i)  
          # draws <- rlnorm(n=1000000, location, shape)
          # https://msalganik.wordpress.com/2017/01/21/making-sense-of-the-rlnorm-function-in-r/
          # plot(bpm)
          mean_bpm <- mean(bpm)
          sd_bpm <- sd(bpm)
          bpm_row <- tibble(mean_bpm = mean_bpm,
                            sd_bpm = sd_bpm)
          bpm_tibble <- rbind(bpm_tibble, bpm_row) 
          bpm_row <- NA
        }
        
        
        mean_bpm_i <- mean(bpm_tibble$mean_bpm)
        se_bpm_i <- sd(bpm_tibble$mean_bpm)     #sd of mean of means
        
        mean_bpm_reps <- bpm_tibble$mean_bpm
        
        # breath_hold_time <- 1/mean_bpm_reps
        # #plot(breath_hold_time)
        # mean(breath_hold_time)
        # sd(breath_hold_time)
        
        # #breaths per day
        # bpd <- 1440/breath_hold_time
        # mean(bpd)
        # sd(bpd)
        # #plot(bpd)
        
        #other option - truncated normal distribution
        #bpm <- rtruncnorm(MC_reps, a=0, b=Inf, mean=bpm_i, sd=bpm_sd_i)
        
        # breaths/day
        bpd <- mean_bpm_reps * 60 * 24
        # plot(bpd)
        bpd_mean_i <-  mean(bpd)
        
        if (MC_var == "all" || MC_var == "Rs"){
          bpd_sd_i <- sd(bpd)  
        } else {
          bpd_sd_i = 0
        }
        
        #tidal volume (mass dependent)
        Vt_i <- Vt_table_i$Vt_mean
        
        if (MC_var == "all" || MC_var == "Vt"){
          Vt_sd_i <- Vt_table_i$Vt_sd  
        } else {
          Vt_sd_i = 0
        }
        
        set.seed(12345)
        Vt <- rnorm(MC_reps, Vt_i, Vt_sd_i)
        Vt_mean_i <- mean(Vt)
        Vt_sd_i <- sd(Vt)
        #plot(Vt)
        
        #Energetic expenditure per day
        Es_perday <- 0.02 * pct_O2* bpd * Vt   
        #plot(Es_perday)
        
        Es_perday_mean <- mean(Es_perday)
        Es_perday_sd <- sd(Es_perday)
        Es_perday_quant025 <- quantile(Es_perday, 0.025, na.rm = TRUE)
        Es_perday_quant975 <- quantile(Es_perday, 0.975, na.rm = TRUE)
        
        #Energettic expenditure per month
        Es = Es_perday * no_days_i
        #plot(Es)
        Es_mean = mean(Es)
        Es_sd = sd(Es)
        Es_quant025 <- quantile(Es, 0.025, na.rm = TRUE)
        Es_quant975 <- quantile(Es, 0.975, na.rm = TRUE)
        
        
        # "age_yrs", "Es", "Es_sd", "quant025", "quant975" 
        row <- tibble(age_yrs = age,
                      Lifestage = Lifestage,
                      Activity_stages = activity,
                      no_days = no_days_i,
                      MC_variable = MC_var,
                      mean_bpm = mean_bpm_i,
                      se_bpm = se_bpm_i,
                      mean_bpd = bpd_mean_i,
                      Vt_mean = Vt_mean_i,
                      Vt_sd = Vt_sd_i,
                      Es_perday = Es_perday_mean, 
                      Es_perday_sd = Es_perday_sd, 
                      Es_perday_quant025 = Es_perday_quant025,
                      Es_perday_quant975  = Es_perday_quant975,
                      Es = Es_mean, 
                      Es_sd = Es_sd,
                      Es_quant025 = Es_quant025, 
                      Es_quant975 = Es_quant975
        )
        
        Es_sensAnalysis_phase2 <- rbind(Es_sensAnalysis_phase2, row)
        
      }
      
    }    
  }
}



kable(Es_sensAnalysis_phase2)


Es_sensAnalysis_phase2 %>% 
  write_csv("data/Es_sensAnalysis_phase2_source_bpm.csv", 
            na = "", append = FALSE)

```

```{r plots_Es_phase2_stacked}
Es_sensAnalysis_phase2 <- read_csv("data/Es_sensAnalysis_phase2_source_bpm.csv")

plot_Es_sensAnalysis_phase2 <- Es_sensAnalysis_phase2 %>% 
  ggplot(aes(x = age_yrs, y = Es))+
  geom_errorbar(aes(ymin = Es - Es_sd, ymax = Es + Es_sd),
                colour = "blue", width = 0.02)+
  geom_point()+
  facet_grid(~MC_variable)+
  ggtitle("Es table - phase 2")

plot_Es_sensAnalysis_phase2


```

```{r Es_phase2_peryear}

#pull out blank Es_subtable
Es_subtable <- Es_sensAnalysis_phase2 %>% dplyr::filter(age_yrs >999, Lifestage == Lifestage)
kable(Es_subtable)


Es_table_2  <- Es_subtable %>%  dplyr::select(age_yrs, Lifestage, no_days, 
                                              MC_variable, Es, Es_sd)

## Calculate sum of Es for ages 1+
for (i in seq(from = 1, to = 31, by = 1)){
  
  for (MC_var in c("all","Rs", "Vt", "pctO2")){
    
    Es_subtable <- Es_sensAnalysis_phase2 %>% dplyr::filter(age_yrs == i & MC_variable == MC_var )
    no_days <- sum(Es_subtable$no_days)
    Es <- sum(Es_subtable$Es)
    Lifestage <- "Juvenile/Adult"
    
    sum_of_variances <- 0
    for (row in 1:nrow(Es_subtable)){
      #for (i in c( 0.33, 0.42, 0.5)){ 
      Es_subtable_i <- Es_subtable[row, "Es"]
      Es_sd_i <- Es_subtable[row, "Es_sd"]
      sum_of_variances <- sum_of_variances + (Es_sd_i)^2
    }
    Es_sd  <-  sqrt(sum_of_variances$Es_sd)
    
    newRow <- tibble(age_yrs = i,
                     Lifestage = Lifestage,
                     no_days = no_days ,
                     MC_variable = MC_var,
                     Es = Es, 
                     Es_sd = Es_sd
    )
    
    Es_table_2 <-
      rbind(Es_table_2, newRow)
  }
}

Es_sensAnalysis_phase2_peryear <- Es_table_2

Es_sensAnalysis_phase2_peryear$Es_perday <-
  Es_sensAnalysis_phase2_peryear$Es / Es_sensAnalysis_phase2_peryear$no_days
Es_sensAnalysis_phase2_peryear$Es_sd_perday <- Es_sensAnalysis_phase2_peryear$Es_sd / Es_sensAnalysis_phase2_peryear$no_days

Es_sensAnalysis_phase2_peryear %>% write_csv("data/Es_sensAnalysis_phase2_peryear_source_bpm.csv", na = "", append = FALSE)

```

```{r plots_Es_phase2_peryear}

plot_Es_sensAnalysis_phase2_peryear <- Es_sensAnalysis_phase2_peryear %>% 
  dplyr::filter(Lifestage == "Juvenile/Adult" & age_yrs >= 1 & age_yrs < 30) %>% 
  ggplot() +
  geom_errorbar(aes(x = age_yrs, ymin = Es_perday - Es_sd_perday, 
                    ymax = Es_perday + Es_sd_perday),
                linetype = 3, colour = 'gray40', width = 0) +
  geom_point(aes(x = age_yrs, y =Es_perday)) +
  facet_grid(~MC_variable)+
  xlab("Age (years)") +
  ylab(bquote('Energetic expenditure (MJ day '^'-1'*')')) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10))+
                     #limits = c(0, 30.5), expand=c(0,0)) +  # max x-axis 30 yrs.
  scale_y_continuous(label=comma,
                     breaks = scales::pretty_breaks(n = 10))+
                     #limits = c(0,1400), expand=c(0,0))+
  theme_bw()+
theme_bw() +
  theme(panel.grid = element_blank())+
  theme(legend.position = 0)+
  # theme(plot.background = element_rect(fill = "black"))+
  # theme(panel.background = element_rect(fill = "black"))+
  theme(panel.border = element_blank())+
  theme(axis.line = element_line(size = 1, colour = "gray75"))+
  theme(axis.text = element_text(colour = "black", size = rel(1.2)))+
  theme(axis.title.y = element_text(colour = "black", 
                                    size = rel(1.4), angle = 90))+
  theme(axis.title.x = element_text(colour = "black", 
                                    size = rel(1.4)))

plot_Es_sensAnalysis_phase2_peryear

```
