---
title: "Production Cost - Phase 1 - per month"
author: "Seline Agbayani"
date: "June 17, 2022 - code updated and cleaned `r format(Sys.time(), '%d %B, %Y')`"
output:
  github_document:
  html_document:

editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(error = TRUE)
knitr::opts_chunk$set(warning = FALSE)

## Setup

# Initialize all libraries, set paths for output figures, then import the gw_observations.csv
# install.packages("tidyr")
# install.packages("tidyverse")
# install.packages("dplyr")
# install.packages("ggplot2")
# install.packages("knitr")
# install.packages("nls2")
# install.packages("nlstools")
# install.packages("nlme")
# install.packages("minpack.lm")
# install.packages("scales")
# install.packages("ggpmisc")
# install.packages("extrafont")


library(tidyr)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(knitr)
library(nls2)
library(nlstools)
library(nlme)
library(minpack.lm)
library(scales)
library(ggpmisc)
library(reshape2)
library(extrafont)

#testing push 

```



```{r declare functions and global variables, include=FALSE}

# **Declare custom functions and global variables**
########## Specify Decimal function ############################
# 
# For use in labelling the plots with equations, and rounding up the coefficients
# to a specific no. of decimal places
specify_decimal <- function(x, k) format(round(x, k), nsmall=k)


############ Multiple plot function######################
#
# ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
# - cols:   Number of columns in layout
# - layout: A matrix specifying the layout. If present, 'cols' is ignored.
#
# If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
# then plot 1 will go in the upper left, 2 will go in the upper right, and
# 3 will go all the way across the bottom.
#
# Code extracted from Cookbook for R. This site is powered by knitr and Jekyll. 
# If you find any errors, please email winston@stdout.org

multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}


########### functions used for carry out the fit ########

## this function is avaible in: 
# http://www.leg.ufpr.br/~walmes/cursoR/ciaeear/as.lm.R   or in 
# https://gist.github.com/TonyLadson/2d63ca70eef92583001dece607127759 (from the line 269)

##### as.lm function: ######

        as.lm <- function(object, ...) UseMethod("as.lm")

        as.lm.nls <- function(object, ...) {
            if (!inherits(object, "nls")) {
                w <- paste("expected object of class nls but got object of class:", 
                    paste(class(object), collapse = " "))
                warning(w)
            }

            gradient <- object$m$gradient()
            if (is.null(colnames(gradient))) {
                colnames(gradient) <- names(object$m$getPars())
            }

            response.name <- if (length(formula(object)) == 2) "0" else 
                as.character(formula(object)[[2]])

            lhs <- object$m$lhs()
            L <- data.frame(lhs, gradient)
            names(L)[1] <- response.name

            fo <- sprintf("%s ~ %s - 1", response.name, 
                paste(colnames(gradient), collapse = "+"))
            fo <- as.formula(fo, env = as.proto.list(L))

            do.call("lm", list(fo, offset = substitute(fitted(object))))

        }

############## End as.lm function 



############### proto function: ############
#### proto function avaible in https://github.com/hadley/proto/blob/master/R/proto.R

proto <- function(. = parent.env(envir), expr = {},
                   envir = new.env(parent = parent.frame()), ...,
                   funEnvir = envir) {
  parent.env(envir) <- .
  envir <- as.proto.environment(envir)  # must do this before eval(...)
  # moved eval after for so that ... always done first
  # eval(substitute(eval(quote({ expr }))), envir)
  dots <- list(...); names <- names(dots)
  for (i in seq_along(dots)) {
    assign(names[i], dots[[i]], envir = envir)
    if (!identical(funEnvir, FALSE) && is.function(dots[[i]]))
      environment(envir[[names[i]]]) <- funEnvir
  }
  eval(substitute(eval(quote({
    expr
  }))), envir)
  if (length(dots))
    as.proto.environment(envir)
  else
    envir
}

#' @export
#' @rdname proto
as.proto <- function(x, ...) {
  UseMethod("as.proto")
}

#' @export
#' @rdname proto
as.proto.environment <- function(x, ...) {
  assign(".that", x, envir = x)
  assign(".super", parent.env(x), envir = x)
  structure(x, class = c("proto", "environment"))
}

#' @export
#' @rdname proto
as.proto.proto <- function(x, ...) {
  x
}
as.proto.list <- function(x, envir, parent, all.names = FALSE, ...,
                          funEnvir = envir, SELECT = function(x) TRUE) {
  if (missing(envir)) {
    if (missing(parent))
      parent <- parent.frame()
    envir <- if (is.proto(parent))
      parent$proto(...)
    else
      proto(parent, ...)
  }
  for (s in names(x))
    if (SELECT(x[[s]])) {
      assign(s, x[[s]], envir = envir)
      if (is.function(x[[s]]) && !identical(funEnvir, FALSE))
        environment(envir[[s]]) <- funEnvir
    }
  if (!missing(parent))
    parent.env(envir) <- parent
  as.proto.environment(envir)  # force refresh of .that and .super
}

#' @export
"$<-.proto" <- function(this,s,value) {
  if (s == ".super")
    parent.env(this) <- value
  if (is.function(value))
    environment(value) <- this
  this[[as.character(substitute(s))]] <- value
  this
}
is.proto <- function(x) inherits(x, "proto")

#' @export
"$.proto" <- function(x, name) {
  inherits <- substr(name, 1, 2) != ".."

  res <- get(name, envir = x, inherits = inherits)
  if (!is.function(res))
    return(res)

  if (deparse(substitute(x)) %in% c(".that", ".super"))
    return(res)

  structure(
    function(...) res(x, ...),
    class = "protoMethod",
    method = res
  )
}

#' @export
print.protoMethod <- function(x, ...) {
  cat("<ProtoMethod>\n")
  print(attr(x, "method"), ...)
}

# modified from Tom Short's original
#' @export
str.proto <- function(object, max.level = 1, nest.lev = 0,
                      indent.str = paste(rep.int(" ", max(0, nest.lev + 1)), collapse = ".."),
                      ...) {
  cat("proto", name.proto(object), "\n")
  Lines <- utils::capture.output(utils::str(
    as.list(object), max.level = max.level,
    nest.lev = nest.lev, ...
  ))[-1]
  for (s in Lines)
    cat(s, "\n")
  if (is.proto(parent.env(object))) {
    cat(indent.str, "parent: ", sep = "")
    utils::str(parent.env(object), nest.lev = nest.lev + 1, ...)
  }
}

#' @export
print.proto <- function(x, ...) {
  if (!exists("proto_print", envir = x, inherits = TRUE))
    return(NextMethod())

  x$proto_print(...)
}

############# End proto function 
        
```   



```{r}       
############ Set path for output figures: ###############
Figurespath <- paste0(getwd(), "/production_cost/figures", collapse = NULL)
Figurespath
############ Set path for input & output data  ###########
datapath <-  paste0(getwd(), "/data", collapse = NULL) 
datapath

```

```{r}
## Read data in (mean mass change)
mass_table <- as_tibble(
  read_csv("data/mass_table.csv"), #monthly
  col_types = (list(cols(age_yrs = col_double(),
                         mean_mass = col_double(),
                         sd_mass = col_double(),
                         mean_lwr = col_double(),
                         mean_upr = col_double(),
                         quant025 = col_double(),
                         quant975 = col_double(),
                         female_mass = col_double(),
                         male_mass = col_double()
                         )
                    )
               )
  )



mean_masschange <- as_tibble(
  read_csv("data/mean_masschange.csv"),
  col_types = (list(cols(age_yrs = col_double(),
                         mean_masschange = col_double(),
                         sd_masschange = col_double(),
                         sex = col_character(),
                         age_mth = col_integer()
                         )
                    )
               )
  )

kable(head(mean_masschange))


age_yr_tibble <- as_tibble(
  read_csv("data/age_yr_tibble.csv"),
  col_types = (list(cols(month = col_character(),
                         no_days_in_mth = col_double(),
                         age_mth = col_double(),
                         no_days_cumul = col_double(),
                         age_yrs = col_double()
                         )
                    )
               )
  )

```



**Calculate Production Costs (P) using equation from Winship et al. 2002**
 P = change in Mass x [(p_lipid x ED_lipid) + (1-p_lipid) x (1-p_water) x ED_protein]

Calculate Production Costs 

```{r}

#########  PRODUCTION COSTS  #########
# 
#Energy density of lipid (MJ/kg)  
#ED_lipid <- 39.3 #39300 KJ/kg * 0.001 - Schmidt-Nielsen (1990)
ED_lipid <- 39.7 #MJ/kg - Sumich 1986 Kleiber 1961

#Energy density of protein (MJ/kg)  
#ED_protein <- 18 #18000 KJ/KG * 0.001  = - Schmidt-Nielsen (1990); Winship et al. (2002)
ED_protein <- 23.7 #MJ/kg  - from Sumich 1986 Kleiber 1961

#From Sumich 1986
# p_lipid_newborn_calf <- 0.33   # based on one observation (highest lipid value observed for neonates)
# p_lipid_adult <-  0.39         # max value for p_lipid based on one A observation (Table 7.1)
p_lipid_min <- 0.33
p_lipid_max <- 0.39


# From Villegas-Amtmann (2015,2017) - values are for Grey whales
#p_lipid_adult <- 0.34         # F_lipid (%lipid mass) - min value for p_lipid
p_protein_nb <- 0.126         # F_protein - fraction newborn protein mass - calculated from muscle and other tissues
p_protein_7mo <- 0.0972       # fraction protein mass up to 7 months 

#Calculated From Rice & Wolman 1971
p_protein_adult_SB <-  0.1062   # fraction of protein in southbound adults (fat)
p_protein_adult_NB <- 0.1086   # fraction of protein in northbound adults (thin)
p_protein_adult <- (p_protein_adult_SB+p_protein_adult_NB)/2       # Avg non-calves NB (0.1086) & SB (0.1062) from Rice and Wolman 2971)

```


Calculate Production Cost per month

```{r}
MC_reps = 10000

P_cost_table <- as_tibble(mean_masschange)  #this table already has age_mth

#add some new columns
P_cost_table$mean_P <- NA
P_cost_table$sd_P <- NA
P_cost_table$quant025 <- NA
P_cost_table$quant975 <-  NA
P_cost_table$p_lipid <-  NA
P_cost_table$p_protein <-  NA
P_cost_table$mass <- NA
P_cost_table$mass_sd <- NA

P_cost_table <- P_cost_table %>% 
  relocate(age_mth) %>%  
  filter(age_mth >= 0)

#Loop through sex and month
for (s in c("N/A", "Female", "Male")){
  for (i in c(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)){ 
    
    #s <- "N/A"
    age <-  i
    
    strcolname <- as.character(age)
    
    mass_change_i <- dplyr::filter(P_cost_table, 
                                   age_mth == age & sex == s)
    mass_chg <- mass_change_i %>% 
      pull(mean_masschange)
    sd <- mass_change_i %>% 
      pull(sd_masschange)
    age_mth <- mass_change_i %>%
      pull(age_mth)
    
    set.seed(12345)
    #rnorm - random normal distribution
    mean_masschange_i <- as_tibble(
      rnorm(MC_reps, mass_chg, sd), col.names = str(i))
    names(mean_masschange_i)[1] <- "mass_chg"
    mean_masschange_i <- mean_masschange_i %>%  
      mutate(age_yrs = strcolname)
    mean_masschange_i <- mean_masschange_i %>%  
      mutate(ID = row_number())
    mean_masschange_i$age_mth <-  age_mth
    
    #pull mean mass and mass sd
    age_yrs_i <- age_yr_tibble %>% 
      filter(age_mth == i) %>% 
      pull(age_yrs) #calculate age_yrs (do not round up)
    
    age_yrs_mid_i <- age_yr_tibble %>% 
      filter(age_mth == i-0.5)  %>% 
      pull(age_yrs)
    
    mass_i <- mass_table %>% 
      filter(round(age_yrs,3) == round(age_yrs_i,3)) %>% 
      pull(mean_mass)
    mass_sd_i <- mass_table %>% 
      filter(round(age_yrs,3) == round(age_yrs_i,3)) %>% 
      pull(sd_mass)
    
    
    
    #min p_lipid 0.34 - Villegas-Amtmann 2017
    #max p_lipid 0.39 - Sumich 1986
    
    p_lipid_i <- as_tibble(
      runif(MC_reps, 
            min = p_lipid_min, 
            max = p_lipid_max),
      col.names = str(i))
    
    names(p_lipid_i)[1] <- "p_lipid"
    
    p_lipid_i <- p_lipid_i %>%  
      mutate(age_yrs = strcolname)
    p_lipid_i <- p_lipid_i %>%  
      mutate(ID = row_number())
    
    mean_masschange_i$p_lipid <- p_lipid_i$p_lipid
    
    #initialize P cost
    mean_masschange_i$P <-NA 
    
    mass_chg_i <- mean_masschange_i$mass_chg
    p_lipid_i <-mean_masschange_i$p_lipid 
    P_cost_i <- mean_masschange_i$P
    age_yrs <- mean_masschange_i$age_yrs
    age_mth <- mean_masschange_i$age_mth  
    
    ####  p_protein_i by month ###
    if (age==0) {
      p_protein_i <-  p_protein_nb
    } else if (age ==1) {
      p_protein_i <-  (p_protein_nb+p_protein_7mo)/2
    } else if (age > 1 & age <= 7) {
      p_protein_i <-  p_protein_7mo
    } else if (age == 8) {
      p_protein_i <- ((p_protein_7mo + p_protein_adult_SB)/2)
    } else if (age > 8 & age <= 12) {
      p_protein_i <-  p_protein_adult_SB
    }
    
    #Calculate Production costs for each age cohort
    P_cost_i <- mass_chg_i*(
      (p_lipid_i * ED_lipid) + 
        (p_protein_i * ED_protein))
    

    mean_P <-  mean(P_cost_i)
    sd_P <- sd(P_cost_i)
    quant025 <- quantile(P_cost_i, 0.025, na.rm = TRUE)
    quant975 <- quantile(P_cost_i, 0.975, na.rm = TRUE)
    
  
    
    
    # Save calculated statistics to P_cost Table 
    P_cost_table$mean_P <- 
      ifelse(P_cost_table$age_mth == age & P_cost_table$sex == s, 
             mean_P, P_cost_table$mean_P)
    P_cost_table$sd_P <- 
      ifelse(P_cost_table$age_mth == age & P_cost_table$sex == s,
             sd_P, P_cost_table$sd_P)
    P_cost_table$quant025 <- 
      ifelse(P_cost_table$age_mth == age & P_cost_table$sex == s,
             quant025, P_cost_table$quant025)
    P_cost_table$quant975 <- 
      ifelse(P_cost_table$age_mth == age & P_cost_table$sex == s,
             quant025, P_cost_table$quant975)
    P_cost_table$p_lipid <- 
      ifelse(P_cost_table$age_mth == age & P_cost_table$sex == s, 
             p_lipid_i, P_cost_table$p_lipid)
    P_cost_table$p_protein <- 
      ifelse(P_cost_table$age_mth == age & P_cost_table$sex == s,
             p_protein_i, P_cost_table$p_protein)
    P_cost_table$mass <- 
      ifelse(P_cost_table$age_mth == age & P_cost_table$sex == s,
             mass_i, P_cost_table$mass)
    P_cost_table$mass_sd <- 
      ifelse(P_cost_table$age_mth == age & P_cost_table$sex == s,
             mass_sd_i, P_cost_table$mass_sd)
    
  }
}



    
kable((P_cost_table))

#No of days in each month
Ts <- c(0,31,28,31,30,31,30,31,31,30,31,30,31,0,31,28,31,30,31,30,31,31,30,31,30,31, 0,31,28,31,30,31,30,31,31,30,31,30,31)

P_cost_table$Ts <- Ts

P_cost_table$mean_masschange_perday <-P_cost_table$mean_masschange / P_cost_table$Ts 
P_cost_table$sd_masschange_perday <-P_cost_table$sd_masschange / P_cost_table$Ts 
P_cost_table$mean_P_perday <- P_cost_table$mean_P / P_cost_table$Ts
P_cost_table$sd_P_perday <-P_cost_table$sd_P / P_cost_table$Ts 

    
kable(head(P_cost_table))

#Save production cost table to file
P_cost_table %>% write_csv("data/P_cost_table_phase1.csv", na = "", append = FALSE)

```




*Plotting Production Cost*

```{r Plot production cost, echo=FALSE}
kable(head(P_cost_table))


plot_PCost <- P_cost_table %>% 
  dplyr::filter(sex == "N/A" & age_mth > 0) %>%
  ggplot() +
  geom_point(aes(x = age_mth-0.5, y= mean_P), size = 2)+
  geom_errorbar(aes(x = age_mth-0.5, 
                    ymin = mean_P - sd_P, 
                    ymax = mean_P + sd_P), 
                width=0, size=1, linetype = 2, color="gray40") +
  xlab("Age (months)") +
  ylab(bquote('Mean production cost (P) in MJ')) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10),
                     limits = c(0, 12)) +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10),
                     limits = c(0, 11000),
                     labels = scales::comma) +
  theme_bw() +
  theme(panel.grid = element_blank(),
        axis.title.x = element_text(size = rel(1.4), colour = "black"),
        axis.text.x = element_text(size = rel(1.2), colour = "black"),
        axis.title.y = element_text(size = rel(1.4), colour = "black"),
        axis.text.y = element_text(size = rel(1.2), colour = "black"),
        strip.background = element_blank(),
        legend.position="none" 
        ) 
    

plot_PCost


```

Production Cost per day

```{r plot Production Cost per day, echo=FALSE}

plot_PCost_perday <- P_cost_table %>% 
  dplyr::filter(sex == "N/A") %>%
  ggplot() +
  geom_point(aes(x = age_mth-0.5, y= mean_P_perday), size = 2)+
  geom_errorbar(aes(x = age_mth-0.5, 
                    ymin = mean_P_perday - sd_P_perday, 
                    ymax = mean_P_perday + sd_P_perday), 
                width=0, size=1, linetype = 2, color="gray40") +
  xlab("Age (months)") +
  ylab(bquote('Mean production cost (P) in MJ day'^'-1')) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10),
                     limits = c(0, 12)) +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10),
                     limits = c(0, 400),
                     labels = scales::comma) +
  theme_bw() +
  theme(panel.grid = element_blank(),
        axis.title.x = element_text(size = rel(1.4), colour = "black"),
        axis.text.x = element_text(size = rel(1.2), colour = "black"),
        axis.title.y = element_text(size = rel(1.2), colour = "black"),
        axis.text.y = element_text(size = rel(1.2), colour = "black"),
        strip.background = element_blank(),
        legend.position="none" 
        ) 
    

plot_PCost_perday


```

Production Cost and Mass 

```{r plot_Pcost_mass, echo=FALSE}

plot_P_cost_mass <- P_cost_table %>%
  dplyr::filter(sex == "N/A") %>%
  ggplot() +
  #mass 
  geom_ribbon(aes(x = age_mth, 
                  ymin = (mass - mass_sd) *2, #secondary axis multiplied by 2 
                  ymax = (mass + mass_sd) *2), #secondary axis multiplied by 2
              fill = "gray", alpha = 0.8)+
  geom_line(aes(x = age_mth, y = mass*2), 
            linetype = 2, 
            linewidth = 0.5, 
            colour = "black")+
  #production cost
  geom_errorbar(aes(x = age_mth-0.5, 
                    ymin = mean_P - sd_P, 
                    ymax = mean_P + sd_P), 
                width=0, 
                linewidth=0.5, 
                linetype = 1, 
                color="gray40") +
  geom_point(aes(x = age_mth-0.5, y= mean_P), size = 2)+
  #axis labels
  xlab("Age (months)") +
  ylab(bquote('Mean production cost (P) in MJ')) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10),
                     limits = c(0, 12)) +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10),
                     limits = c(0, 13000),
                     labels = scales::comma,
                     #secondary axis = primary axis divided by 2
                     sec.axis=sec_axis(~./2, name = "Mass (kg)",
                                       labels = scales::comma,
                                       breaks = scales::pretty_breaks(n = 5))
                     )+
                     #breaks = scales::pretty_breaks(n = 8))+
                       #limits = c(0, 50)) +
  theme_bw() + 
  theme(panel.grid = element_blank())+
  theme(legend.position = "none")+
    theme(legend.background = element_rect(fill = "white"))+
    theme(legend.text = element_text(colour = "black", size = rel(1)))+
    theme(legend.key = element_rect(fill = "transparent"))+ #colour = "transparent"))+
    ggtitle(element_blank()) +
    theme(plot.background = element_rect(fill = "white"))+
    theme(panel.background = element_rect(fill = "white"))+
    theme(panel.border = element_blank())+
    theme(axis.line = element_line(colour = "black"))+
    theme(axis.text = element_text(colour = "black", size = rel(1.2)))+
    theme(axis.title.y = element_text(colour = "black", 
                                      size = rel(1.4), 
                                      angle = 90, 
                                      margin = margin(t = 0, r = 10, b = 0, l = 0)))+
    theme(axis.title.x = element_text(colour = "black", size = rel(1.4)))+
    theme(axis.ticks = element_line(colour="black"))+
    theme(axis.title.y.right  = element_text(colour = "black", 
                                      size = rel(1.2), 
                                      angle = 270, 
                                      margin = margin(t = 0, r = 0, b = 0, l = 10)))
  


plot_P_cost_mass


```



Production Cost and Mass per day

```{r plot_Pcost_perday_mass, echo=FALSE}

plot_P_cost_mass_perday <- P_cost_table %>%
  dplyr::filter(sex == "N/A") %>%
  ggplot() +
  # geom_errorbar(aes(x = age_mth-0.5, 
  #                   ymin = (mass - mass_sd) /50, 
  #                 ymax = (mass + mass_sd) /50), 
  #               width=0, size=1, linetype = 2, color="gray40") +
  geom_ribbon(aes(x = age_mth, 
                  ymin = (mass - mass_sd) /12, 
                  ymax = (mass + mass_sd) /12), 
              fill = "gray", alpha = 0.8)+
  geom_line(aes(x = age_mth, y = mass/12), 
             linetype = 2, size = 0.5, colour = "black")+
  geom_errorbar(aes(x = age_mth-0.5, 
                    ymin = mean_P_perday - sd_P_perday, 
                    ymax = mean_P_perday + sd_P_perday), 
                width=0, size=0.5, linetype = 1, color="gray40") +
  geom_point(aes(x = age_mth-0.5, y= mean_P_perday), size = 2)+
  xlab("Age (months)") +
  ylab(bquote('Mean production cost (P) in MJ day'^'-1')) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10),
                     limits = c(0, 12)) +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10),
                     limits = c(0, 550),
                     labels = scales::comma,
                     sec.axis=sec_axis(~.*12, name = "Mass (kg)",
                                       labels = scales::comma,
                                       breaks = scales::pretty_breaks(n = 10))
                     
                     )+
                     #breaks = scales::pretty_breaks(n = 8))+
                       #limits = c(0, 50)) +
  theme_bw() + 
  theme(panel.grid = element_blank())+
  theme(legend.position = "none")+
    theme(legend.background = element_rect(fill = "white"))+
    theme(legend.text = element_text(colour = "black", size = rel(1)))+
    theme(legend.key = element_rect(fill = "transparent"))+ #colour = "transparent"))+
    ggtitle(element_blank()) +
    theme(plot.background = element_rect(fill = "white"))+
    theme(panel.background = element_rect(fill = "white"))+
    theme(panel.border = element_blank())+
    theme(axis.line = element_line(colour = "black"))+
    theme(axis.text = element_text(colour = "black", size = rel(1.2)))+
    theme(axis.title.y = element_text(colour = "black", 
                                      size = rel(1.4), 
                                      angle = 90, 
                                      margin = margin(t = 0, r = 10, b = 0, l = 0)))+
    theme(axis.title.x = element_text(colour = "black", size = rel(1.4)))+
    theme(axis.ticks = element_line(colour="black"))+
    theme(axis.title.y.right  = element_text(colour = "black", 
                                      size = rel(1.2), 
                                      angle = 270, 
                                      margin = margin(t = 0, r = 0, b = 0, l = 10)))+
    annotate("text", x= 12, y = 25,
             label = "Production cost", 
             hjust = 1,
             size = rel(4),
             color = "black") +
    annotate("text", x= 12, y = 550,
             label = "Mass", 
             hjust = 1,
             size = rel(4),
             color = "black")
  
  


plot_P_cost_mass_perday


```





```{r Pcost from birth to weaning, echo=FALSE}
# Production cost from birth to weaning  (from 0 to 10th mth, i.e. 304 days)

# mass_at_birth_tibble <- mass_table %>% filter(age_yrs == 0)  #at birth
# 
# mass_at_birth_mean <- mass_at_birth_tibble$mean_mass 
# mass_at_birth_sd <- mass_at_birth_tibble$sd_mass
# 
# age_at_weaning_tibble <- age_yr_tibble %>% filter(age_mth == 10)
# age_yrs_at_weaning <- age_at_weaning_tibble$age_yrs
# mass_at_weaning_tibble <- mass_table %>%  filter(age_yrs == age_yrs_at_weaning)  #10th mth  i.e. 0.8333333
# 
# mass_at_weaning_mean <-mass_at_weaning_tibble$mean_mass 
# mass_at_weaning_sd <-mass_at_weaning_tibble$sd_mass
# 
# 
# MC_reps = 10000
# 
# set.seed(12345)
# mass_at_birth_reps <- rnorm(MC_reps, mass_at_birth_mean, mass_at_birth_sd)
# mass_at_weaning_reps <- rnorm(MC_reps, mass_at_weaning_mean, mass_at_weaning_sd)
# 
# masschange_lactation_reps <- mass_at_weaning_reps - mass_at_birth_reps
# 
# masschange_lactation_mean <- mean(masschange_lactation_reps)
# masschange_lactation_sd <- sd(masschange_lactation_reps)
# 
# masschange_lactation_mean
# masschange_lactation_sd
# 
# 
# p_lipid_young_reps <- runif(MC_reps, min = 0.33, max = 0.39)
# 
# P_cost_birth_to_weaning_reps <- masschange_lactation_reps*((p_lipid_young_reps * ED_lipid) + 
#                                                         (p_protein_nb * ED_protein))
#            
# P_cost_birth_to_weaning_mean <- mean(P_cost_birth_to_weaning_reps)
# P_cost_birth_to_weaning_mean
# 
# P_cost_birth_to_weaning_sd <- sd(P_cost_birth_to_weaning_reps)
# P_cost_birth_to_weaning_sd
# 
# P_cost_birth_to_weaning_quant025 <-  quantile(P_cost_birth_to_weaning_reps, 0.025, na.rm = TRUE)         
# P_cost_birth_to_weaning_quant025
# 
# P_cost_birth_to_weaning_quant975 <-  quantile(P_cost_birth_to_weaning_reps, 0.975, na.rm = TRUE)         
# P_cost_birth_to_weaning_quant975        
# 
# 
# # Ts from 0 to 10th month = 304 days
# age_yr_tibble_10mth <- age_yr_tibble %>% filter(age_mth == 10)
# Ts_birth_to_weaning <-  age_yr_tibble_10mth$no_days_cumul
# P_cost_birth_to_weaning_mean_perday <- P_cost_birth_to_weaning_mean / Ts_birth_to_weaning
# P_cost_birth_to_weaning_sd_perday <- P_cost_birth_to_weaning_sd / Ts_birth_to_weaning
# 
# P_cost_birth_to_weaning_perday_reps <- rnorm(MC_reps,P_cost_birth_to_weaning_mean_perday,P_cost_birth_to_weaning_sd_perday )
# 
# P_cost_birth_to_weaning_perday_quant025 <- quantile(P_cost_birth_to_weaning_perday_reps, 0.025, na.rm = TRUE) 
# P_cost_birth_to_weaning_perday_quant975 <- quantile(P_cost_birth_to_weaning_perday_reps, 0.975, na.rm = TRUE) 
# 
# 
# 
# P_cost_birth_to_weaning_tibble <- as.data.frame(matrix(ncol = 11, nrow = 0))
# 
# cnames <- c("time_period", "Ts", "sex", 
#             "P_cost_mean", "P_cost_sd", "P_quant025", "P_quant975",
#             "P_cost_mean_perday", "P_cost_sd_perday", "P_perday_quant025", "P_perday_quant975")            
# 
# colnames(P_cost_birth_to_weaning_tibble) <- cnames
# 
# P_cost_birth_to_weaning_tibble <- as_tibble(P_cost_birth_to_weaning_tibble,
#                                             col_types = (list(ID = col_integer(),
#                                                               time_period =  col_character(),
#                                                               Ts = col_double(),
#                                                               sex = col_character(), 
#                                                               P_cost_mean = col_double(), 
#                                                               P_cost_sd = col_double(), 
#                                                               P_quant025 = col_double(), 
#                                                               P_quant975 = col_double(),
#                                                               P_cost_mean_perday = col_double(),
#                                                               P_cost_sd_perday = col_double(),
#                                                               P_cost_perday_quant025 = col_double(),
#                                                               P_cost_perday_quant975 = col_double()
#                                             )
#                                             )
# )
# 
# 
# row <-  tibble(time_period = "birth to weaning",
#                Ts = Ts_birth_to_weaning,
#                sex = "N/A",
#                P_cost_mean = P_cost_birth_to_weaning_mean,
#                P_cost_sd = P_cost_birth_to_weaning_sd,
#                P_quant025 = P_cost_birth_to_weaning_quant025,
#                P_quant975 = P_cost_birth_to_weaning_quant975,
#                P_cost_mean_perday = P_cost_birth_to_weaning_mean_perday,
#                P_cost_sd_perday =  P_cost_birth_to_weaning_sd_perday,
#                P_cost_perday_quant025 = P_cost_birth_to_weaning_perday_quant025,
#                P_cost_perday_quant975 = P_cost_birth_to_weaning_perday_quant975
#         )
# 
# 
#         
# P_cost_birth_to_weaning_tibble <- rbind(P_cost_birth_to_weaning_tibble, row)
# 
# 
# 
# kable(P_cost_birth_to_weaning_tibble)
# 
# 
# P_cost_birth_to_weaning_tibble %>% write_csv("data/P_cost_birth_to_weaning_tibble.csv", na = "", append = FALSE)


```



```{r Pcost from birth to 6th month, echo=FALSE}
#Production cost from birth to 6th mth (# days)

# mass_at_birth_tibble <- mass_table %>% filter(age_yrs == 0)  #at birth
# 
# mass_at_birth_mean <- mass_at_birth_tibble$mean_mass 
# mass_at_birth_sd <- mass_at_birth_tibble$sd_mass
# 
# age_at_6mths_tibble <- age_yr_tibble %>% filter(age_mth == 6)
# age_yrs_at_6mths <- age_at_6mths_tibble$age_yrs
# mass_at_6mths_tibble <- mass_table %>%  filter(age_yrs == age_yrs_at_6mths)  #10th mth  i.e. 0.8333333
# 
# mass_at_6mths_mean <-mass_at_6mths_tibble$mean_mass 
# mass_at_6mths_sd <-mass_at_6mths_tibble$sd_mass
# 
# 
# MC_reps = 10000
# 
# set.seed(12345)
# mass_at_birth_reps <- rnorm(MC_reps, mass_at_birth_mean, mass_at_birth_sd)
# mass_at_6mths_reps <- rnorm(MC_reps, mass_at_6mths_mean, mass_at_6mths_sd)
# 
# masschange_lactation_reps <- mass_at_6mths_reps - mass_at_birth_reps
# 
# masschange_lactation_mean <- mean(masschange_lactation_reps)
# masschange_lactation_sd <- sd(masschange_lactation_reps)
# 
# masschange_lactation_mean
# masschange_lactation_sd
# 
# 
# p_lipid_young_reps <- runif(MC_reps, min = 0.33, max = 0.38)
# 
# P_cost_birth_to_6mths_reps <- masschange_lactation_reps*((p_lipid_young_reps * ED_lipid) + 
#                                                         (p_protein_nb * ED_protein))
#            
# P_cost_birth_to_6mths_mean <- mean(P_cost_birth_to_6mths_reps)
# P_cost_birth_to_6mths_mean
# 
# P_cost_birth_to_6mths_sd <- sd(P_cost_birth_to_6mths_reps)
# P_cost_birth_to_6mths_sd
# 
# P_cost_birth_to_6mths_quant025 <-  quantile(P_cost_birth_to_6mths_reps, 0.025, na.rm = TRUE)         
# P_cost_birth_to_6mths_quant025
# 
# P_cost_birth_to_6mths_quant975 <-  quantile(P_cost_birth_to_6mths_reps, 0.975, na.rm = TRUE)         
# P_cost_birth_to_6mths_quant975        
# 
# 
# # Ts from 0 to 6h month = 181
# age_yr_tibble_6mth <- age_yr_tibble %>% filter(age_mth == 6)
# Ts_birth_to_6mths <-  age_yr_tibble_6mth$no_days_cumul
# 
# P_cost_birth_to_6mths_mean_perday <- P_cost_birth_to_6mths_mean / Ts_birth_to_6mths
# P_cost_birth_to_6mths_sd_perday <- P_cost_birth_to_6mths_sd / Ts_birth_to_6mths
# 
# P_cost_birth_to_6mths_perday_reps <- rnorm(MC_reps,P_cost_birth_to_6mths_mean_perday,P_cost_birth_to_6mths_sd_perday )
# 
# P_cost_birth_to_6mths_perday_quant025 <- quantile(P_cost_birth_to_6mths_perday_reps, 0.025, na.rm = TRUE) 
# P_cost_birth_to_6mths_perday_quant975 <- quantile(P_cost_birth_to_6mths_perday_reps, 0.975, na.rm = TRUE) 
# 
# 
# 
# P_cost_birth_to_6mths_tibble <- as.data.frame(matrix(ncol = 11, nrow = 0))
# 
# cnames <- c("time_period", "Ts", "sex", 
#             "P_cost_mean", "P_cost_sd", "P_quant025", "P_quant975",
#             "P_cost_mean_perday", "P_cost_sd_perday", "P_perday_quant025", "P_perday_quant975")            
# 
# colnames(P_cost_birth_to_6mths_tibble) <- cnames
# 
# P_cost_birth_to_6mths_tibble <- as_tibble(P_cost_birth_to_6mths_tibble,
#                                             col_types = (list(ID = col_integer(),
#                                                               time_period =  col_character(),
#                                                               Ts = col_double(),
#                                                               sex = col_character(), 
#                                                               P_cost_mean = col_double(), 
#                                                               P_cost_sd = col_double(), 
#                                                               P_quant025 = col_double(), 
#                                                               P_quant975 = col_double(),
#                                                               P_cost_mean_perday = col_double(),
#                                                               P_cost_sd_perday = col_double(),
#                                                               P_cost_perday_quant025 = col_double(),
#                                                               P_cost_perday_quant975 = col_double()
#                                             )
#                                             )
# )
# 
# 
# row <-  tibble(time_period = "birth to 6mths",
#                Ts = Ts_birth_to_6mths,
#                sex = "N/A",
#                P_cost_mean = P_cost_birth_to_6mths_mean,
#                P_cost_sd = P_cost_birth_to_6mths_sd,
#                P_quant025 = P_cost_birth_to_6mths_quant025,
#                P_quant975 = P_cost_birth_to_6mths_quant975,
#                P_cost_mean_perday = P_cost_birth_to_6mths_mean_perday,
#                P_cost_sd_perday =  P_cost_birth_to_6mths_sd_perday,
#                P_cost_perday_quant025 = P_cost_birth_to_6mths_perday_quant025,
#                P_cost_perday_quant975 = P_cost_birth_to_6mths_perday_quant975
#         )
# 
# 
#         
# P_cost_birth_to_6mths_tibble <- rbind(P_cost_birth_to_6mths_tibble, row)
# 
# 
# 
# kable(P_cost_birth_to_6mths_tibble)
# 
# 
# P_cost_birth_to_6mths_tibble %>% write_csv("data/P_cost_birth_to_6mths_tibble.csv", na = "", append = FALSE)


```




